<?php
require __DIR__.'/app/bootstrap.php';
$slug=trim($_GET['slug']??'');$s=db()->prepare('SELECT * FROM brands WHERE slug=? AND is_active=1');$s->execute([$slug]);$brand=$s->fetch();if(!$brand){http_response_code(404);exit('Marka bulunamadı.');}
page_view('brand',(int)$brand['id']);
$sort=$_GET['sort']??'popular';$stock=!empty($_GET['stock']);$min=$_GET['min']??'';$max=$_GET['max']??'';$page=max(1,(int)($_GET['p']??1));$perPage=24;
$where=['p.brand_id=?','p.is_active=1'];$params=[(int)$brand['id']];if($stock)$where[]='p.stock>0';if($min!==''){$where[]='p.sale_price>=?';$params[]=(float)$min;}if($max!==''){$where[]='p.sale_price<=?';$params[]=(float)$max;}
$order='p.sales_count DESC,p.is_featured DESC,p.id DESC';if($sort==='new')$order='p.id DESC';elseif($sort==='price_asc')$order='p.sale_price ASC';elseif($sort==='price_desc')$order='p.sale_price DESC';elseif($sort==='name')$order='p.name ASC';
$c=db()->prepare('SELECT COUNT(*) FROM products p WHERE '.implode(' AND ',$where));$c->execute($params);$total=(int)$c->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));if($page>$pages)$page=$pages;$offset=($page-1)*$perPage;
$sql="SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE ".implode(' AND ',$where)." ORDER BY $order LIMIT $perPage OFFSET $offset";$s=db()->prepare($sql);$s->execute($params);$products=$s->fetchAll();
$banners=active_banners('brand_top');$banner=$banners[0]??null;
$pageTitle=$brand['name'].' Ürünleri | TOPLUCA';$pageDescription=mb_substr(strip_tags((string)($brand['description']?:$brand['name'].' ürünlerini TOPLUCA’da avantajlı fiyatlarla keşfedin.')),0,155);$pageKeywords=$brand['name'].', '.$brand['name'].' ürünleri, TOPLUCA';$pageCanonical=app_url('brand.php?slug='.urlencode($brand['slug']));
function brand_query(array $changes=[]): string{$q=$_GET;foreach($changes as $k=>$v){if($v===null)unset($q[$k]);else$q[$k]=$v;}return http_build_query($q);}
require __DIR__.'/includes/header.php';
?>
<?php if($banner):?><section class="category-campaign"><div class="container"><a class="managed-banner managed-banner-category" href="<?=h($banner['link_url']?app_url($banner['link_url']):'#')?>"<?php if($banner['desktop_image']):?> style="--desktop-bg:url('<?=h(app_url($banner['desktop_image']))?>');--overlay:<?=h($banner['overlay_color']?:'#000000')?>;--opacity:<?=h((string)$banner['overlay_opacity'])?>"<?php endif;?>><div><small><?=h($banner['eyebrow']??'')?></small><h2><?=h($banner['title'])?></h2><p><?=h($banner['subtitle']??'')?></p><?php if($banner['button_text']):?><span><?=h($banner['button_text'])?> →</span><?php endif;?></div></a></div></section><?php endif;?>
<section class="brand-hero"><div class="container brand-hero-inner"><div><?php if($brand['logo']):?><div class="brand-hero-logo"><img src="<?=app_url($brand['logo'])?>" alt="<?=h($brand['name'])?>"></div><?php endif;?><small>MARKA</small><h1><?=h($brand['name'])?></h1><p><?=h($brand['description']?:$brand['name'].' ürünlerini TOPLUCA’da avantajlı fiyatlar ve güçlü teslimat seçenekleriyle inceleyin.')?></p></div><div class="brand-hero-count"><strong><?=number_format($total,0,',','.')?></strong><span>aktif ürün</span></div></div></section>
<section class="section"><div class="container"><div class="toolbar"><div class="toolbar-left"><strong><?=number_format($total,0,',','.')?> ürün</strong><form class="brand-quick-filter" method="get"><input type="hidden" name="slug" value="<?=h($slug)?>"><input type="number" name="min" placeholder="Min TL" value="<?=h((string)$min)?>"><input type="number" name="max" placeholder="Maks TL" value="<?=h((string)$max)?>"><label><input type="checkbox" name="stock" value="1" <?=$stock?'checked':''?>> Stokta</label><button>Uygula</button></form></div><form method="get"><input type="hidden" name="slug" value="<?=h($slug)?>"><input type="hidden" name="min" value="<?=h((string)$min)?>"><input type="hidden" name="max" value="<?=h((string)$max)?>"><?php if($stock):?><input type="hidden" name="stock" value="1"><?php endif;?><select name="sort" onchange="this.form.submit()"><option value="popular" <?=$sort==='popular'?'selected':''?>>Önerilen</option><option value="new" <?=$sort==='new'?'selected':''?>>En yeniler</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Fiyat artan</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Fiyat azalan</option><option value="name" <?=$sort==='name'?'selected':''?>>İsme göre</option></select></form></div><?php if(!$products):?><div class="empty"><h3>Aktif ürün bulunamadı</h3><p>Filtreleri temizleyerek tekrar deneyebilirsiniz.</p><a class="primary-btn" href="<?=app_url('brand.php?slug='.urlencode($slug))?>">Filtreleri Temizle</a></div><?php else:?><div class="products-grid"><?php foreach($products as $p){require __DIR__.'/includes/product-card.php';}?></div><?php endif;?><?php if($pages>1):?><nav class="pagination"><?php if($page>1):?><a href="?<?=h(brand_query(['p'=>$page-1]))?>">←</a><?php endif;?><?php for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++):?><a class="<?=$i===$page?'active':''?>" href="?<?=h(brand_query(['p'=>$i]))?>"><?=$i?></a><?php endfor;?><?php if($page<$pages):?><a href="?<?=h(brand_query(['p'=>$page+1]))?>">→</a><?php endif;?></nav><?php endif;?></div></section>
<?php require __DIR__.'/includes/footer.php';?>