<?php
require __DIR__.'/app/bootstrap.php';
$slug=trim((string)($_GET['slug']??''));$category=category_by_slug($slug);if(!$category){http_response_code(404);exit('Kategori bulunamadı.');}
view_event('category',(int)$category['id']);$path=category_path($category);$children=child_categories((int)$category['id']);$ids=descendant_ids((int)$category['id']);$ph=implode(',',array_fill(0,count($ids),'?'));
$brand=(int)($_GET['brand']??0);$min=($_GET['min']??'')!==''?(float)$_GET['min']:null;$max=($_GET['max']??'')!==''?(float)$_GET['max']:null;$stock=!empty($_GET['stock']);$free=!empty($_GET['free']);$same=!empty($_GET['same_day']);$sort=(string)($_GET['sort']??'recommended');$page=max(1,(int)($_GET['page']??1));$per=24;$offset=($page-1)*$per;
$where="p.is_active=1 AND p.category_id IN ($ph)";$params=$ids;
if($brand){$where.=' AND p.brand_id=?';$params[]=$brand;}if($min!==null){$where.=' AND p.sale_price>=?';$params[]=$min;}if($max!==null){$where.=' AND p.sale_price<=?';$params[]=$max;}if($stock)$where.=' AND (p.stock-p.reserved_stock)>0';if($free)$where.=" AND p.shipping_policy='free'";if($same)$where.=' AND p.same_day_delivery=1';
$order=match($sort){'price_asc'=>'p.sale_price ASC','price_desc'=>'p.sale_price DESC','new'=>'p.id DESC','sales'=>'p.sales_count DESC',default=>'p.is_bestseller DESC,p.is_featured DESC,p.sales_count DESC,p.id DESC'};
$countSql="SELECT COUNT(*) FROM products p WHERE $where";$s=db()->prepare($countSql);$s->execute($params);$total=(int)$s->fetchColumn();$pages=max(1,(int)ceil($total/$per));
$sql="SELECT p.*,b.name brand_name,b.slug brand_slug,c.name category_name,c.slug category_slug FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE $where ORDER BY $order LIMIT $per OFFSET $offset";$s=db()->prepare($sql);$s->execute($params);$products=$s->fetchAll();
$brandSql="SELECT b.id,b.name,COUNT(*) total FROM products p JOIN brands b ON b.id=p.brand_id WHERE p.is_active=1 AND p.category_id IN ($ph) GROUP BY b.id,b.name ORDER BY total DESC,b.name";$bs=db()->prepare($brandSql);$bs->execute($ids);$brands=$bs->fetchAll();
$pageTitle=$category['name'].' | TOPLUCA';$pageDescription=$category['meta_description']?:$category['name'].' ürünleri TOPLUCA’da.';
function current_qs(array $replace=[]): string {$q=$_GET;foreach($replace as $k=>$v){if($v===null)unset($q[$k]);else$q[$k]=$v;}return http_build_query($q);}
require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="shell"><div class="breadcrumbs"><a href="<?=url()?>">Anasayfa</a><?php foreach($path as $p):?><span>›</span><a href="<?=url('category.php?slug='.urlencode($p['slug']))?>"><?=h($p['name'])?></a><?php endforeach;?></div><h1><?=h($category['name'])?></h1><p><?=h($category['description']?:$category['name'].' kategorisindeki ürünleri marka, fiyat, stok ve teslimat seçeneklerine göre kolayca filtreleyin.')?></p><div class="category-banner"><div><h2><?=h($category['name'])?> ürünlerinde <b>fırsatları kaçırma!</b></h2><p>Stoktan hızlı gönderim, Ankara’da uygun ürünlerde aynı gün teslimat ve avantajlı fiyatlar.</p></div><div class="category-banner__art"><?=match($category['icon_key']??''){ 'book'=>'📚','monitor'=>'💻','printer'=>'🖨️','paper'=>'📄','bag'=>'🎒','palette'=>'🎨',default=>'✏️'}?></div></div></div></section>
<section class="section"><div class="shell catalog-layout">
<aside class="filters-panel" data-filters><div class="filter-mobile-head"><b>Filtreler</b><button type="button" data-filter-close>×</button></div>
  <div class="filter-group"><h4>Kategori</h4><div class="filter-tree"><?php foreach($path as $p):?><a class="<?=$p['id']==$category['id']?'active':''?>" href="<?=url('category.php?slug='.urlencode($p['slug']))?>"><span><?=h($p['name'])?></span><b>›</b></a><?php endforeach;?><?php foreach($children as $c):?><a href="<?=url('category.php?slug='.urlencode($c['slug']))?>"><span><?=h($c['name'])?></span><b>›</b></a><?php endforeach;?></div></div>
  <form method="get"><input type="hidden" name="slug" value="<?=h($slug)?>">
  <div class="filter-group"><h4>Marka</h4><input class="filter-search" type="search" placeholder="Marka ara..." data-local-filter="brands"><div data-filter-list="brands"><?php foreach($brands as $b):?><label class="filter-check"><input type="radio" name="brand" value="<?=(int)$b['id']?>" <?=$brand===(int)$b['id']?'checked':''?>><span><?=h($b['name'])?> (<?=(int)$b['total']?>)</span></label><?php endforeach;?></div></div>
  <div class="filter-group"><h4>Fiyat Aralığı</h4><div class="filter-price"><input type="number" name="min" placeholder="₺ Min" value="<?=h($_GET['min']??'')?>"><input type="number" name="max" placeholder="₺ Maks" value="<?=h($_GET['max']??'')?>"></div><button class="filter-apply">Uygula</button></div>
  <div class="filter-group"><h4>Stok & Teslimat</h4><label class="filter-check"><input type="checkbox" name="stock" value="1" <?=$stock?'checked':''?>>Stokta Olanlar</label><label class="filter-check"><input type="checkbox" name="free" value="1" <?=$free?'checked':''?>>Ücretsiz Kargo</label><label class="filter-check"><input type="checkbox" name="same_day" value="1" <?=$same?'checked':''?>>Ankara Aynı Gün Teslimat</label><button class="filter-apply">Filtreleri Uygula</button></div>
  </form>
</aside>
<div>
  <div class="catalog-toolbar"><button class="mobile-filter-trigger" type="button" data-filter-open>☰ Filtrele</button><div class="catalog-toolbar__count"><b><?=number_format($total,0,',','.')?></b> ürün listeleniyor</div><div class="catalog-toolbar__right"><span style="font-size:10px;color:#777">Sıralama:</span><form method="get"><?php foreach($_GET as $k=>$v)if($k!=='sort'&&$k!=='page'):?><input type="hidden" name="<?=h($k)?>" value="<?=h($v)?>"><?php endif;?><select name="sort" data-auto-submit><option value="recommended">Önerilen</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Fiyat Artan</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Fiyat Azalan</option><option value="sales" <?=$sort==='sales'?'selected':''?>>En Çok Satan</option><option value="new" <?=$sort==='new'?'selected':''?>>Yeni Gelenler</option></select></form></div></div>
  <?php if($brand||$min!==null||$max!==null||$stock||$free||$same):?><div class="active-filters"><?php if($brand):?><a class="active-filter" href="?<?=h(current_qs(['brand'=>null,'page'=>null]))?>">Marka ×</a><?php endif;?><?php if($min!==null||$max!==null):?><a class="active-filter" href="?<?=h(current_qs(['min'=>null,'max'=>null,'page'=>null]))?>">Fiyat ×</a><?php endif;?><?php if($stock):?><a class="active-filter" href="?<?=h(current_qs(['stock'=>null,'page'=>null]))?>">Stokta ×</a><?php endif;?><?php if($free):?><a class="active-filter" href="?<?=h(current_qs(['free'=>null,'page'=>null]))?>">Ücretsiz Kargo ×</a><?php endif;?><?php if($same):?><a class="active-filter" href="?<?=h(current_qs(['same_day'=>null,'page'=>null]))?>">Ankara Aynı Gün ×</a><?php endif;?><a class="active-filter" style="color:#e54f00" href="<?=url('category.php?slug='.urlencode($slug))?>">Tümünü Temizle</a></div><?php endif;?>
  <?php if(!$products):?><div class="empty-state"><div class="empty-state__icon">🔎</div><h2>Bu filtrelere uygun ürün bulunamadı.</h2><p>Filtreleri temizleyip tekrar deneyebilirsiniz.</p><a class="primary-btn" href="<?=url('category.php?slug='.urlencode($slug))?>">Filtreleri Temizle</a></div><?php else:?><div class="products-grid catalog-products"><?php foreach($products as $product)require __DIR__.'/includes/product-card.php';?></div><?php endif;?>
  <?php if($pages>1):?><nav style="display:flex;justify-content:center;gap:6px;margin-top:22px" aria-label="Sayfalama"><?php for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++):?><a href="?<?=h(current_qs(['page'=>$i]))?>" style="width:36px;height:36px;display:grid;place-items:center;border:1px solid #e0e3e6;border-radius:8px;<?=$i===$page?'background:#ff5a00;color:white;border-color:#ff5a00':''?>"><?=$i?></a><?php endfor;?></nav><?php endif;?>
</div></div></section>
<?php require __DIR__.'/includes/footer.php';?>
