<?php
require __DIR__.'/app/bootstrap.php';
$slug=trim($_GET['slug']??'');
$s=db()->prepare('SELECT * FROM categories WHERE slug=? AND is_active=1');$s->execute([$slug]);$cat=$s->fetch();
if(!$cat){http_response_code(404);exit('Kategori bulunamadı.');}
page_view('category',(int)$cat['id']);
$ids=category_descendants((int)$cat['id']);$ph=implode(',',array_fill(0,count($ids),'?'));
$brand=(int)($_GET['brand']??0);$min=$_GET['min']??'';$max=$_GET['max']??'';$stock=!empty($_GET['stock']);$free=!empty($_GET['free']);$sort=$_GET['sort']??'popular';$page=max(1,(int)($_GET['p']??1));$perPage=24;
$selectedAttrs=is_array($_GET['attr']??null)?$_GET['attr']:[];
$where=["p.category_id IN ($ph)",'p.is_active=1'];$params=$ids;
if($brand){$where[]='p.brand_id=?';$params[]=$brand;}if($min!==''){$where[]='p.sale_price>=?';$params[]=(float)$min;}if($max!==''){$where[]='p.sale_price<=?';$params[]=(float)$max;}if($stock)$where[]='p.stock>0';if($free)$where[]="p.shipping_policy='free'";
foreach($selectedAttrs as $key=>$value){if(!is_string($key)||!is_string($value)||$value==='')continue;$where[]='EXISTS(SELECT 1 FROM product_attributes pax WHERE pax.product_id=p.id AND pax.filter_key=? AND pax.attribute_value=?)';$params[]=$key;$params[]=$value;}
$order='p.sales_count DESC,p.is_featured DESC,p.id DESC';if($sort==='price_asc')$order='p.sale_price ASC';elseif($sort==='price_desc')$order='p.sale_price DESC';elseif($sort==='new')$order='p.id DESC';elseif($sort==='name')$order='p.name ASC';
$countSql='SELECT COUNT(*) FROM products p WHERE '.implode(' AND ',$where);$cs=db()->prepare($countSql);$cs->execute($params);$total=(int)$cs->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));if($page>$pages)$page=$pages;$offset=($page-1)*$perPage;
$sql="SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE ".implode(' AND ',$where)." ORDER BY $order LIMIT $perPage OFFSET $offset";$s=db()->prepare($sql);$s->execute($params);$products=$s->fetchAll();
$brandSql="SELECT DISTINCT b.* FROM brands b JOIN products p ON p.brand_id=b.id WHERE p.category_id IN ($ph) AND p.is_active=1 AND b.is_active=1 ORDER BY b.name";$bs=db()->prepare($brandSql);$bs->execute($ids);$brands=$bs->fetchAll();$selectedBrandName='';foreach($brands as $b){if((int)$b['id']===$brand){$selectedBrandName=(string)$b['name'];break;}}
$facetSql="SELECT pa.filter_key,MIN(pa.attribute_name) attribute_name,pa.attribute_value,COUNT(DISTINCT pa.product_id) total FROM product_attributes pa JOIN products p ON p.id=pa.product_id WHERE p.category_id IN ($ph) AND p.is_active=1 AND pa.filter_key IS NOT NULL AND pa.filter_key<>'' GROUP BY pa.filter_key,pa.attribute_value ORDER BY attribute_name,pa.attribute_value";$fs=db()->prepare($facetSql);$fs->execute($ids);$facets=[];foreach($fs->fetchAll() as $r){$facets[$r['filter_key']]['name']=$r['attribute_name'];$facets[$r['filter_key']]['values'][]=$r;}
$children=category_children((int)$cat['id']);$categoryBanners=active_banners('category_top');$banner=$categoryBanners[0]??null;
$pageTitle=trim((string)($cat['meta_title']??''))!==''?$cat['meta_title']:$cat['name'].' | TOPLUCA';$pageDescription=trim((string)($cat['meta_description']??''))!==''?$cat['meta_description']:mb_substr(strip_tags((string)($cat['description']??'')),0,155);if($pageDescription==='')$pageDescription=$cat['name'].' ürünlerini TOPLUCA’da inceleyin.';$pageKeywords=trim((string)($cat['meta_keywords']??''))!==''?$cat['meta_keywords']:$cat['name'].', TOPLUCA';$pageCanonical=app_url('category.php?slug='.urlencode($cat['slug']));
function category_query(array $changes=[]): string{$q=$_GET;foreach($changes as $k=>$v){if($v===null)unset($q[$k]);else$q[$k]=$v;}return http_build_query($q);}
require __DIR__.'/includes/header.php';
?>
<?php if($banner):?><section class="category-campaign"><div class="container"><a class="managed-banner managed-banner-category" href="<?=h(storefront_link($banner['link_url']??''))?>"<?php if($banner['desktop_image']):?> style="--desktop-bg:url('<?=h(app_url($banner['desktop_image']))?>');--overlay:<?=h($banner['overlay_color']?:'#000000')?>;--opacity:<?=h((string)$banner['overlay_opacity'])?>"<?php endif;?>><div><small><?=h($banner['eyebrow']??'')?></small><h2><?=h($banner['title'])?></h2><p><?=h($banner['subtitle']??'')?></p><?php if($banner['button_text']):?><span><?=h($banner['button_text'])?> →</span><?php endif;?></div></a></div></section><?php endif;?>
<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?=app_url()?>">Ana Sayfa</a><span>›</span><span><?=h($cat['name'])?></span></div><h1><?=h($cat['name'])?></h1><p><?=number_format($total,0,',','.')?> ürün bulundu</p></div></section>
<section class="section"><div class="container listing-layout">
<aside class="filter-panel" data-filter-panel><button class="filter-close" type="button" data-filter-close>Filtreleri Kapat ×</button>
<?php if($children):?><div class="filter-section"><h4>Alt Kategoriler</h4><?php foreach($children as $ch):?><a href="<?=app_url('category.php?slug='.urlencode($ch['slug']))?>"><?=h($ch['name'])?></a><?php endforeach;?></div><?php endif;?>
<form method="get"><input type="hidden" name="slug" value="<?=h($slug)?>"><input type="hidden" name="sort" value="<?=h($sort)?>">
<div class="filter-section"><h4>Marka</h4><select name="brand"><option value="0">Tüm Markalar</option><?php foreach($brands as $b):?><option value="<?=(int)$b['id']?>" <?=$brand===(int)$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select></div>
<div class="filter-section"><h4>Fiyat Aralığı</h4><div class="price-filter"><input type="number" step="0.01" name="min" placeholder="Min" value="<?=h((string)$min)?>"><input type="number" step="0.01" name="max" placeholder="Maks" value="<?=h((string)$max)?>"></div></div>
<?php foreach(array_slice($facets,0,8,true) as $key=>$facet):?><div class="filter-section"><h4><?=h($facet['name'])?></h4><select name="attr[<?=h($key)?>]"><option value="">Tümü</option><?php foreach(array_slice($facet['values'],0,30) as $v):?><option value="<?=h($v['attribute_value'])?>" <?=isset($selectedAttrs[$key])&&$selectedAttrs[$key]===$v['attribute_value']?'selected':''?>><?=h($v['attribute_value'])?> (<?=(int)$v['total']?>)</option><?php endforeach;?></select></div><?php endforeach;?>
<div class="filter-section"><label><input type="checkbox" name="stock" value="1" <?=$stock?'checked':''?>> Sadece stoktakiler</label><label><input type="checkbox" name="free" value="1" <?=$free?'checked':''?>> Ücretsiz kargo</label></div><div class="filter-section"><button class="filter-apply">Filtreleri Uygula</button><a class="filter-reset" href="<?=app_url('category.php?slug='.urlencode($slug))?>">Filtreleri temizle</a></div></form></aside>
<div>
<?php if($brand||$min!==''||$max!==''||$stock||$free||array_filter($selectedAttrs)):?><div class="selected-chips"><span class="chip">Filtreler aktif</span><?php if($selectedBrandName!==''):?><a class="chip" href="?<?=h(category_query(['brand'=>null,'p'=>null]))?>">Marka: <?=h($selectedBrandName)?> ×</a><?php endif;?><?php foreach($selectedAttrs as $k=>$v):if($v==='')continue;$copy=$selectedAttrs;unset($copy[$k]);?><a class="chip" href="?<?=h(category_query(['attr'=>$copy?:null,'p'=>null]))?>"><?=h(($facets[$k]['name']??$k).': '.$v)?> ×</a><?php endforeach;?></div><?php endif;?>
<div class="toolbar"><div class="toolbar-left"><button class="filter-open" type="button" data-filter-open>☰ Filtrele</button><strong><?=number_format($total,0,',','.')?> ürün</strong></div><form method="get"><?php foreach($_GET as $k=>$v):if(in_array($k,['sort','p'],true))continue;if(is_array($v)){foreach($v as $ak=>$av):?><input type="hidden" name="<?=h($k)?>[<?=h($ak)?>]" value="<?=h($av)?>"><?php endforeach;}else:?><input type="hidden" name="<?=h($k)?>" value="<?=h($v)?>"><?php endif;endforeach;?><select name="sort" onchange="this.form.submit()"><option value="popular" <?=$sort==='popular'?'selected':''?>>Önerilen sıralama</option><option value="new" <?=$sort==='new'?'selected':''?>>En yeniler</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Fiyat artan</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Fiyat azalan</option><option value="name" <?=$sort==='name'?'selected':''?>>İsme göre</option></select></form></div>
<?php if(!$products):?><div class="empty"><h3>Ürün bulunamadı</h3><p>Filtreleri değiştirerek tekrar deneyebilirsiniz.</p></div><?php else:?><div class="products-grid"><?php foreach($products as $p){require __DIR__.'/includes/product-card.php';}?></div><?php endif;?>
<?php if($pages>1):?><nav class="pagination" aria-label="Sayfalar"><?php if($page>1):?><a href="?<?=h(category_query(['p'=>$page-1]))?>">←</a><?php endif;?><?php for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++):?><a class="<?=$i===$page?'active':''?>" href="?<?=h(category_query(['p'=>$i]))?>"><?=$i?></a><?php endfor;?><?php if($page<$pages):?><a href="?<?=h(category_query(['p'=>$page+1]))?>">→</a><?php endif;?></nav><?php endif;?>
</div></div></section>
<?php require __DIR__.'/includes/footer.php';?>