<?php
require __DIR__.'/app/bootstrap.php';
$slug=trim($_GET['slug']??'');
$s=db()->prepare('SELECT * FROM categories WHERE slug=? AND is_active=1');$s->execute([$slug]);$category=$s->fetch();if(!$category){http_response_code(404);exit('Kategori bulunamadı.');}
$ids=[(int)$category['id']];$q=$ids;while($q){$current=array_shift($q);$c=db()->prepare('SELECT id FROM categories WHERE parent_id=? AND is_active=1');$c->execute([$current]);foreach($c->fetchAll() as $r){$ids[]=(int)$r['id'];$q[]=(int)$r['id'];}}
$ph=implode(',',array_fill(0,count($ids),'?'));$params=$ids;$where="p.category_id IN ($ph) AND p.is_active=1";
$brand=(int)($_GET['brand']??0);if($brand){$where.=' AND p.brand_id=?';$params[]=$brand;}if(isset($_GET['stock']))$where.=' AND p.stock>0';if(isset($_GET['free']))$where.=" AND p.shipping_policy='free'";
$sort=$_GET['sort']??'recommended';$order=match($sort){'price_asc'=>'p.sale_price ASC','price_desc'=>'p.sale_price DESC','new'=>'p.id DESC','sales'=>'p.sales_count DESC',default=>'p.is_featured DESC,p.sales_count DESC,p.id DESC'};
$s=db()->prepare("SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE $where ORDER BY $order LIMIT 100");$s->execute($params);$products=$s->fetchAll();
$brands=db()->query('SELECT * FROM brands WHERE is_active=1 ORDER BY name')->fetchAll();$childrenStmt=db()->prepare('SELECT * FROM categories WHERE parent_id=? AND is_active=1 ORDER BY sort_order,name');$childrenStmt->execute([(int)$category['id']]);$children=$childrenStmt->fetchAll();$pageTitle=$category['name'].' | TOPLUCA';require __DIR__.'/includes/header.php';
?>
<section class="page-head"><div class="container"><div class="breadcrumb"><a href="<?=url()?>">Ana Sayfa</a><span>›</span><?=h($category['name'])?></div><h1><?=h($category['name'])?></h1><p><?=count($products)?> ürün listeleniyor</p></div></section>
<section class="section"><div class="container listing"><aside class="filters" data-filter-panel><div class="filter-head"><strong>Filtreler</strong><button type="button" data-filter-close>×</button></div><?php if($children):?><div class="filter-block"><h4>Alt Kategoriler</h4><?php foreach($children as $c):?><a style="display:block;margin:7px 0;font-size:13px" href="<?=url('category.php?slug='.urlencode($c['slug']))?>"><?=h($c['name'])?></a><?php endforeach;?></div><?php endif;?><form><input type="hidden" name="slug" value="<?=h($slug)?>"><div class="filter-block"><h4>Marka</h4><select name="brand"><option value="">Tüm Markalar</option><?php foreach($brands as $b):?><option value="<?=(int)$b['id']?>" <?=$brand===(int)$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select></div><div class="filter-block"><label><input type="checkbox" name="stock" value="1" <?=isset($_GET['stock'])?'checked':''?>> Sadece stoktakiler</label><label><input type="checkbox" name="free" value="1" <?=isset($_GET['free'])?'checked':''?>> Ücretsiz kargo</label></div><button>Filtreyi Uygula</button></form></aside><div><div class="toolbar"><button class="filter-open" type="button" data-filter-open>☰ Filtrele</button><strong><?=count($products)?> ürün</strong><form><input type="hidden" name="slug" value="<?=h($slug)?>"><select name="sort" onchange="this.form.submit()"><option value="recommended">Önerilen</option><option value="sales" <?=$sort==='sales'?'selected':''?>>En Çok Satan</option><option value="price_asc" <?=$sort==='price_asc'?'selected':''?>>Fiyat Artan</option><option value="price_desc" <?=$sort==='price_desc'?'selected':''?>>Fiyat Azalan</option><option value="new" <?=$sort==='new'?'selected':''?>>Yeni Gelenler</option></select></form></div><div class="products-grid"><?php foreach($products as $p) require __DIR__.'/includes/product-card.php';?></div></div></div></section>
<?php require __DIR__.'/includes/footer.php';
