<?php
require __DIR__.'/app/bootstrap.php';
$items=cart_items();if(!$items)redirect('cart.php');$subtotal=cart_subtotal();$error='';$shippingCompanies=db()->query('SELECT * FROM shipping_companies WHERE is_active=1 ORDER BY price')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_check();$name=trim($_POST['customer_name']??'');$email=trim($_POST['customer_email']??'');$phone=trim($_POST['customer_phone']??'');$city=trim($_POST['city']??'');$district=trim($_POST['district']??'');$address=trim($_POST['address']??'');$delivery=$_POST['delivery_method']??'cargo';$carrierId=(int)($_POST['shipping_company_id']??0);
    if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$phone||!$city||!$address)$error='Lütfen zorunlu alanları doğru doldurun.';
    $shipping=0;$carrier='';
    if(!$error){
        $allFree=true;$allSame=true;foreach($items as $i){if($i['shipping_policy']!=='free')$allFree=false;if(!(int)$i['same_day_delivery'])$allSame=false;}
        if($delivery==='same_day'){
            if(mb_strtolower($city,'UTF-8')!=='ankara')$error='Aynı gün teslimat yalnızca Ankara için kullanılabilir.';
            if(!$allSame)$error='Sepetinizde aynı gün teslimata uygun olmayan ürün bulunuyor.';
            if(date('H:i')>(string)setting('same_day_cutoff','15:00'))$error='Bugünkü aynı gün teslimat sipariş saati sona erdi.';
            $cap=(int)setting('same_day_daily_capacity',50);$used=(int)db()->query("SELECT COUNT(*) FROM orders WHERE delivery_method='same_day' AND DATE(created_at)=CURDATE()")->fetchColumn();if($used>=$cap)$error='Bugünkü aynı gün teslimat kapasitesi doldu.';
            if(!$error&&$subtotal<(float)setting('same_day_free_limit',2000))$shipping=(float)setting('same_day_under_limit_fee',149.90);$carrier='TOPLUCA Ankara Aynı Gün';
        }else{
            if(!$allFree&&$subtotal<(float)setting('free_shipping_limit',500)){$s=db()->prepare('SELECT * FROM shipping_companies WHERE id=? AND is_active=1');$s->execute([$carrierId]);$c=$s->fetch();if(!$c)$error='Lütfen kargo firması seçin.';else{$shipping=(float)$c['price'];$carrier=$c['name'];}}else $carrier='Ücretsiz Standart Kargo';
        }
    }
    if(!$error){
        try{db()->beginTransaction();$orderNo='TPL'.date('ymd').strtoupper(substr(bin2hex(random_bytes(4)),0,6));$total=$subtotal+$shipping;$s=db()->prepare('INSERT INTO orders(order_no,customer_name,customer_email,customer_phone,city,district,address,subtotal,shipping_total,grand_total,delivery_method,shipping_company_name,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,\'new\',NOW(),NOW())');$s->execute([$orderNo,$name,$email,$phone,$city,$district,$address,$subtotal,$shipping,$total,$delivery,$carrier]);$oid=(int)db()->lastInsertId();foreach($items as $i){if((int)$i['stock']<(int)$i['quantity'])throw new RuntimeException($i['name'].' için yeterli stok yok.');$s=db()->prepare('INSERT INTO order_items(order_id,product_id,product_name,sku,quantity,unit_price,unit_cost,line_total) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$oid,$i['id'],$i['name'],$i['sku'],$i['quantity'],$i['sale_price'],$i['purchase_price'],$i['line_total']]);db()->prepare('UPDATE products SET stock=stock-?,sales_count=sales_count+? WHERE id=?')->execute([$i['quantity'],$i['quantity'],$i['id']]);}db()->prepare('UPDATE carts SET converted_order_id=?,subtotal=?,updated_at=NOW() WHERE id=?')->execute([$oid,$subtotal,cart_id()]);db()->commit();$_SESSION['last_order_no']=$orderNo;redirect('order-success.php');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
    }
}
$pageTitle='Siparişi Tamamla | TOPLUCA';require __DIR__.'/includes/header.php';
?><section class="page-head"><div class="container"><h1>Siparişi Tamamla</h1></div></section><section class="section"><div class="container cart-layout"><form class="summary" method="post"><?=csrf_field()?><?php if($error):?><div class="flash error"><?=h($error)?></div><?php endif;?><h3>Teslimat Bilgileri</h3><p><input style="width:100%;padding:10px" name="customer_name" placeholder="Ad Soyad" required></p><p><input style="width:100%;padding:10px" type="email" name="customer_email" placeholder="E-posta" required></p><p><input style="width:100%;padding:10px" name="customer_phone" placeholder="Telefon" required></p><p><input style="width:100%;padding:10px" name="city" placeholder="İl (örn. Ankara)" required></p><p><input style="width:100%;padding:10px" name="district" placeholder="İlçe"></p><p><textarea style="width:100%;padding:10px;min-height:100px" name="address" placeholder="Açık adres" required></textarea></p><h3>Teslimat</h3><p><label><input type="radio" name="delivery_method" value="cargo" checked> Standart Kargo</label></p><?php if((int)setting('same_day_enabled',1)===1):?><p><label><input type="radio" name="delivery_method" value="same_day"> Ankara Aynı Gün Teslimat</label></p><?php endif;?><h3>Kargo Firması</h3><?php foreach($shippingCompanies as $idx=>$c):?><p><label><input type="radio" name="shipping_company_id" value="<?=(int)$c['id']?>" <?=$idx===0?'checked':''?>> <?=h($c['name'])?> — <?=money($c['price'])?></label></p><?php endforeach;?><div class="notice">V1 ödeme yöntemi: Havale/EFT. Kart ödeme sağlayıcısı daha sonra güvenli API ile bağlanmalıdır.</div><button class="checkout" style="border:0;width:100%">Siparişi Oluştur</button></form><aside class="summary"><h3>Sipariş Özeti</h3><?php foreach($items as $i):?><div><span><?=h($i['name'])?> × <?=(int)$i['quantity']?></span><strong><?=money($i['line_total'])?></strong></div><?php endforeach;?><hr><div class="total"><span>Ara Toplam</span><strong><?=money($subtotal)?></strong></div></aside></div></section><?php require __DIR__.'/includes/footer.php';
