<?php
require __DIR__.'/app/bootstrap.php';
$pageTitle='İletişim & Yardım | TOPLUCA';
$pageDescription='TOPLUCA müşteri desteği, sipariş takibi ve iletişim bilgileri.';
require __DIR__.'/includes/header.php';
$phone=trim((string)setting('company_phone',''));
$email=trim((string)setting('company_email',''));
$address=trim((string)setting('company_address',''));
?>
<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?=app_url()?>">Ana Sayfa</a><span>›</span><span>İletişim</span></div><h1>Yardım & İletişim</h1><p>Ürün, sipariş, teslimat ve kurumsal alım sorularınız için doğru kanala hızlıca ulaşın.</p></div></section>
<section class="section"><div class="container contact-layout"><div class="contact-main"><span class="eyebrow">MÜŞTERİ DESTEĞİ</span><h2>Size nasıl yardımcı olabiliriz?</h2><p>İletişim bilgileri WebYönet → Site & SEO Ayarları alanından yönetilir. Burada yalnızca sisteme kaydettiğiniz gerçek bilgiler gösterilir.</p><div class="contact-cards"><?php if($phone!==''):?><a class="contact-card" href="tel:<?=h(preg_replace('/[^0-9+]/','',$phone))?>"><span>☎</span><div><small>Telefon</small><strong><?=h($phone)?></strong></div></a><?php endif;?><?php if($email!==''):?><a class="contact-card" href="mailto:<?=h($email)?>"><span>✉</span><div><small>E-posta</small><strong><?=h($email)?></strong></div></a><?php endif;?><?php if($address!==''):?><div class="contact-card"><span>⌖</span><div><small>Adres</small><strong><?=nl2br(h($address))?></strong></div></div><?php endif;?></div><?php if($phone===''&&$email===''&&$address===''):?><div class="empty"><h3>İletişim bilgileri henüz girilmedi</h3><p>WebYönet üzerinden firma telefon, e-posta ve adres bilgilerini ekleyebilirsiniz.</p></div><?php endif;?></div><aside class="support-panel"><div><span class="support-icon">⌕</span><h3>Siparişinizi mi arıyorsunuz?</h3><p>Benzersiz TOPLUCA sipariş kodunuz ve e-posta adresinizle güncel durumu görüntüleyin.</p><a class="primary-btn" href="<?=app_url('order-track.php')?>">Siparişimi Takip Et →</a></div><div><span class="support-icon">♙</span><h3>Üye hesabınız</h3><p>Sipariş geçmişinizi ve kayıtlı adreslerinizi hesabınızdan yönetin.</p><a class="secondary-btn" href="<?=app_url('account.php')?>">Hesabıma Git →</a></div></aside></div></section>
<?php require __DIR__.'/includes/footer.php';?>