<?php
require __DIR__.'/app/bootstrap.php';page_view('home');$pageTitle='TOPLUCA | Kırtasiye, Kitap, Teknoloji ve Ofis';
$cats=main_categories();$products=db()->query("SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.is_active=1 ORDER BY p.is_bestseller DESC,p.sales_count DESC,p.id DESC LIMIT 10")->fetchAll();
$featured=db()->query("SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.is_active=1 ORDER BY p.is_featured DESC,p.id DESC LIMIT 10")->fetchAll();
$brands=db()->query("SELECT * FROM brands WHERE is_active=1 ORDER BY sort_order,name LIMIT 14")->fetchAll();
$hero=db()->query("SELECT * FROM banners WHERE position_code='home_hero' AND is_active=1 AND (start_at IS NULL OR start_at<=NOW()) AND (end_at IS NULL OR end_at>=NOW()) ORDER BY sort_order,id LIMIT 1")->fetch();
$midL=db()->query("SELECT * FROM banners WHERE position_code='home_mid_left' AND is_active=1 ORDER BY sort_order,id LIMIT 1")->fetch();$midR=db()->query("SELECT * FROM banners WHERE position_code='home_mid_right' AND is_active=1 ORDER BY sort_order,id LIMIT 1")->fetch();
require __DIR__.'/includes/header.php';?>
<section class="hero"><div class="container hero-grid"><div class="hero-main"<?php if($hero&&$hero['desktop_image']):?> style="background-image:linear-gradient(90deg,rgba(255,96,0,.96),rgba(255,96,0,.60)),url('<?=app_url($hero['desktop_image'])?>');background-size:cover;background-position:center"<?php endif;?>><div class="hero-copy"><span class="eyebrow">TOPLUCA.NET</span><h1><?=h($hero['title']??'İhtiyacın olan her şey')?> <span>TOPLUCA’da!</span></h1><p><?=h($hero['subtitle']??'Kırtasiye, kitap, teknoloji ve ofis ihtiyaçlarını tek sepette, hızlı ve düzenli alışveriş deneyimiyle buluşturuyoruz.')?></p><a class="secondary-btn" href="<?=app_url($hero['link_url']??'search.php')?>"><?=h($hero['button_text']??'Alışverişe Başla')?> →</a></div></div><div class="hero-side"><div class="feature-tile"><div class="icon">⚡</div><div><strong>Ankara’da Aynı Gün</strong><span>Adres ve sepete göre otomatik uygunluk kontrolü</span></div></div><div class="feature-tile"><div class="icon">▤</div><div><strong>Toplu Alım Avantajı</strong><span>Adet arttıkça otomatik kademeli fiyat</span></div></div><div class="feature-tile"><div class="icon">⌕</div><div><strong>Akıllı Arama & Filtre</strong><span>Barkod, ISBN, marka, kategori ve eş anlamlı arama</span></div></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><small>Kategoriler</small><h2>Ne arıyorsanız burada</h2></div></div><div class="category-grid"><?php foreach($cats as $c):?><a class="category-card" href="<?=app_url('category.php?slug='.urlencode($c['slug']))?>"><span class="cat-icon"><?=h($c['icon']?:'•')?></span><strong><?=h($c['name'])?></strong><span>Ürünleri incele →</span></a><?php endforeach;?></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><div><small>Popüler</small><h2>Çok Satanlar</h2></div><a href="<?=app_url('search.php')?>">Tüm ürünler →</a></div><div class="products-grid"><?php foreach($products as $p){require __DIR__.'/includes/product-card.php';}?></div></div></section>
<section class="section"><div class="container"><div class="promo-grid"><a class="promo-card orange" href="<?=app_url($midL['link_url']??'category.php?slug=kitap')?>"><small>TOPLUCA FIRSATLARI</small><h3><?=h($midL['title']??'Kitaplarda Avantajlı Fiyatlar')?></h3><span><?=h($midL['button_text']??'Kitapları İncele')?> →</span></a><a class="promo-card" href="<?=app_url($midR['link_url']??'category.php?slug=bilgisayar-sarf-malzemeleri')?>"><small>TEKNOLOJİ</small><h3><?=h($midR['title']??'Bilgisayar & Aksesuar Fırsatları')?></h3><span><?=h($midR['button_text']??'Ürünleri İncele')?> →</span></a></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><div><small>Sizin için</small><h2>Öne Çıkan Ürünler</h2></div></div><div class="products-grid"><?php foreach($featured as $p){require __DIR__.'/includes/product-card.php';}?></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><small>Markalar</small><h2>Popüler Markalar</h2></div></div><div class="brand-strip"><?php foreach($brands as $b):?><a class="brand-box" href="<?=app_url('brand.php?slug='.urlencode($b['slug']))?>"><?php if($b['logo']):?><img src="<?=app_url($b['logo'])?>" alt="<?=h($b['name'])?>"><?php else:?><?=h($b['name'])?><?php endif;?></a><?php endforeach;?></div></div></section>
<?php require __DIR__.'/includes/footer.php';?>