<?php
require __DIR__.'/app/bootstrap.php';
$slug=trim((string)($_GET['slug']??''));
$s=db()->prepare("SELECT p.*,b.name brand_name,b.slug brand_slug,c.name category_name,c.slug category_slug FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.is_active=1 LIMIT 1");$s->execute([$slug]);$product=$s->fetch();if(!$product){http_response_code(404);exit('Ürün bulunamadı.');}
view_event('product',(int)$product['id']);db()->prepare('UPDATE products SET view_count=view_count+1 WHERE id=?')->execute([(int)$product['id']]);
$images=product_images((int)$product['id'],$product['image']);$attrs=product_attributes((int)$product['id']);$tiers=[];$s=db()->prepare('SELECT * FROM product_price_tiers WHERE product_id=? AND is_active=1 ORDER BY min_qty');$s->execute([(int)$product['id']]);$tiers=$s->fetchAll();$price=effective_price($product,1);$old=(float)($product['compare_price']?:$product['sale_price']);$discount=$old>$price?(int)round((1-$price/$old)*100):0;
$related=product_card_query('p.category_id=? AND p.id<>?',[(int)$product['category_id'],(int)$product['id']],'p.sales_count DESC,p.id DESC',5);
$pageTitle=($product['meta_title']?:$product['name'].' | TOPLUCA');$pageDescription=$product['meta_description']?:($product['short_description']?:$product['name'].' ürününü TOPLUCA güvencesiyle satın alın.');
require __DIR__.'/includes/header.php';
?>
<section class="product-page"><div class="shell">
<div class="breadcrumbs"><a href="<?=url()?>">Anasayfa</a><span>›</span><a href="<?=url('category.php?slug='.urlencode($product['category_slug']))?>"><?=h($product['category_name'])?></a><span>›</span><span><?=h($product['name'])?></span></div>
<div class="product-main">
  <div class="product-gallery">
    <div class="thumb-list"><?php foreach($images as $i=>$img):?><button class="thumb <?=$i===0?'active':''?>" type="button" data-thumb data-src="<?=url($img['image_path'])?>" data-alt="<?=h($img['alt_text']?:$product['name'])?>"><img src="<?=url($img['image_path'])?>" alt=""></button><?php endforeach;?></div>
    <div class="main-image"><img data-main-image src="<?=url($images[0]['image_path']??$product['image'])?>" alt="<?=h($product['name'])?>"><span class="zoom-hint">⌕ Görseli incelemek için üzerine gelin</span></div>
  </div>
  <div class="product-info">
    <div class="product-info__topline"><span class="product-info__badge"><?=((int)$product['is_bestseller']===1)?'Çok Satan':'TOPLUCA Seçimi'?></span><span>Ürün Kodu: <?=h($product['sku'])?><?=!empty($product['barcode'])?' · Barkod: '.h($product['barcode']):''?></span></div>
    <h1><?=h($product['name'])?></h1>
    <div class="product-info__rating"><b>★★★★★</b><span><?=h((string)$product['rating_avg'])?> / 5</span><span>(<?=(int)$product['review_count']?> değerlendirme)</span></div>
    <div class="brand-row"><span>Marka: <a href="<?=url('brand.php?slug='.urlencode($product['brand_slug']??''))?>"><?=h($product['brand_name']??'TOPLUCA')?></a></span><span><?=((int)$product['stock']-(int)$product['reserved_stock'])>0?'✓ Stokta':'Stokta Yok'?></span></div>
    <div class="feature-list"><?php foreach(array_slice($attrs,0,5) as $a):?><div><b><?=h($a['attribute_name'])?>:</b> <?=h($a['attribute_value'])?></div><?php endforeach;?><?php if(!$attrs):?><div>Stoktan hızlı gönderim</div><div>Güvenli alışveriş altyapısı</div><div>Kolay sipariş takibi</div><?php endif;?></div>
    <div class="product-buy-price"><strong><?=money($price)?></strong><?php if($old>$price):?><del><?=money($old)?></del><?php endif;?><?php if($discount):?><em>%<?=$discount?> İndirim</em><?php endif;?></div>
    <?php if($tiers):?><div class="bulk-price-box"><b>Toplu Alım Fiyatları</b><?php foreach($tiers as $t):?><div class="bulk-tier"><span><?=(int)$t['min_qty']?><?=!empty($t['max_qty'])?' - '.(int)$t['max_qty']:'+')?> adet</span><strong><?=money($t['unit_price'])?> / adet</strong></div><?php endforeach;?></div><?php endif;?>
    <div class="buy-row">
      <div class="qty-control" data-qty><button type="button" data-minus>−</button><input form="product-add-form" type="number" name="quantity" min="<?=max(1,(int)$product['min_order_qty'])?>" max="<?=max(1,(int)$product['stock']-(int)$product['reserved_stock'])?>" value="<?=max(1,(int)$product['min_order_qty'])?>"><button type="button" data-plus>+</button></div>
      <form id="product-add-form" method="post" action="<?=url('cart.php')?>"><?=csrf_field()?><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?=(int)$product['id']?>"><button class="buy-button" type="submit">🛒 Sepete Ekle</button></form>
      <form method="post" action="<?=url('favorites.php')?>"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="product_id" value="<?=(int)$product['id']?>"><button class="favorite-button" type="submit">♡ Favorilere Ekle</button></form>
    </div>
    <div class="product-delivery-grid"><div><b><?=($product['shipping_policy']==='free')?'🚚 Ücretsiz Kargo':'🚚 Hızlı Kargo'?></b><span><?=($product['shipping_policy']==='free')?'Tüm siparişlerde':'Sepet limitine göre ücretsiz'?></span></div><div><b><?=((int)$product['same_day_delivery']===1)?'📍 Ankara’da Aynı Gün':'📍 Standart Teslimat'?></b><span><?=((int)$product['same_day_delivery']===1)?h((string)setting('same_day_cutoff','15:00')).' öncesi uygun siparişlerde':'Kargo ile teslim'?></span></div><div><b>✓ Stok Var</b><span>Hızlı gönderim için hazır</span></div></div>
  </div>
</div>
<div class="product-tabs" data-tabs>
  <div class="tab-nav"><button class="active" type="button" data-tab="description">Ürün Açıklaması</button><button type="button" data-tab="specs">Teknik Özellikler</button><button type="button" data-tab="reviews">Yorumlar (<?=(int)$product['review_count']?>)</button><button type="button" data-tab="delivery">Teslimat & İade</button></div>
  <div class="tab-panel active" data-panel="description"><div class="product-detail-grid"><div class="product-copy"><h3><?=h($product['short_description']?:$product['name'])?></h3><p><?=nl2br(h($product['description']?:$product['short_description']))?></p><div class="icon-features"><div class="icon-feature"><span>🚚</span><b>Hızlı Teslimat</b><small>Stoktan gönderim</small></div><div class="icon-feature"><span>🛡</span><b>Güvenli Sipariş</b><small>Korunan oturum</small></div><div class="icon-feature"><span>📦</span><b>Sağlam Paketleme</b><small>Ürüne uygun paket</small></div><div class="icon-feature"><span>↩</span><b>Kolay İade</b><small>Süreç takibi</small></div></div></div><div class="specs"><h3>Öne Çıkan Bilgiler</h3><table class="spec-table"><tr><th>Marka</th><td><?=h($product['brand_name']??'TOPLUCA')?></td></tr><tr><th>Stok Kodu</th><td><?=h($product['sku'])?></td></tr><?php if($product['barcode']):?><tr><th>Barkod</th><td><?=h($product['barcode'])?></td></tr><?php endif;?><?php if($product['isbn']):?><tr><th>ISBN</th><td><?=h($product['isbn'])?></td></tr><?php endif;?><tr><th>KDV</th><td>%<?=h((string)$product['vat_rate'])?></td></tr><tr><th>Stok</th><td><?=max(0,(int)$product['stock']-(int)$product['reserved_stock'])?> adet</td></tr></table></div></div></div>
  <div class="tab-panel" data-panel="specs"><table class="spec-table"><?php if($attrs):foreach($attrs as $a):?><tr><th><?=h($a['attribute_name'])?></th><td><?=h($a['attribute_value'])?></td></tr><?php endforeach;else:?><tr><th>Marka</th><td><?=h($product['brand_name']??'TOPLUCA')?></td></tr><tr><th>Model</th><td><?=h($product['model_number']??'-')?></td></tr><?php endif;?></table></div>
  <div class="tab-panel" data-panel="reviews"><div class="empty-state" style="padding:28px"><div class="empty-state__icon">⭐</div><h2>Ürün değerlendirmeleri</h2><p>Yorum altyapısı hazırdır. Onaylı alışveriş değerlendirmeleri burada listelenir.</p></div></div>
  <div class="tab-panel" data-panel="delivery"><h3>Teslimat Mantığı</h3><p>Adresiniz Ankara ise sistem ilçe, saat, günlük kapasite, sepet tutarı ve sepetteki ürünlerin uygunluğunu kontrol ederek aynı gün teslimat seçeneğini sunar. Diğer illerde yalnızca uygun standart kargo seçenekleri gösterilir.</p></div>
</div>
</div></section>
<?php if($related):?><section class="section section--soft"><div class="shell"><div class="section-head"><div class="section-head__copy"><small>SİZE ÖZEL</small><h2>Benzer Ürünler</h2></div><a href="<?=url('category.php?slug='.urlencode($product['category_slug']))?>">Tümünü Gör →</a></div><div class="products-grid"><?php foreach($related as $product)require __DIR__.'/includes/product-card.php';?></div></div></section><?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>
