<?php
$searches=db()->query("SELECT search_term,COUNT(*) searches,MAX(result_count) max_results,SUM(result_count=0) noresult FROM search_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY search_term ORDER BY searches DESC LIMIT 50")->fetchAll();
$abandoned=db()->query("SELECT c.*,TIMESTAMPDIFF(MINUTE,c.updated_at,NOW()) idle_minutes FROM carts c WHERE c.converted_order_id IS NULL AND c.subtotal>0 ORDER BY c.updated_at DESC LIMIT 100")->fetchAll();
$topProducts=db()->query("SELECT p.id,p.name,p.sku,p.view_count,p.sales_count,p.sale_price,p.purchase_price,COALESCE(SUM(oi.quantity),0) sold,COALESCE(SUM(oi.line_total),0) revenue FROM products p LEFT JOIN order_items oi ON oi.product_id=p.id LEFT JOIN orders o ON o.id=oi.order_id AND o.status<>'cancelled' GROUP BY p.id ORDER BY revenue DESC,p.sales_count DESC LIMIT 30")->fetchAll();
$todayViews=(int)db()->query("SELECT COUNT(*) FROM page_views WHERE DATE(created_at)=CURDATE()")->fetchColumn();$monthOrders=(int)db()->query("SELECT COUNT(*) FROM orders WHERE created_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')")->fetchColumn();$monthRevenue=(float)db()->query("SELECT COALESCE(SUM(grand_total),0) FROM orders WHERE created_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01') AND status<>'cancelled'")->fetchColumn();
?>
<div class="admin-page-head"><div><span class="eyebrow">RAPORLAMA</span><h2>Analiz Merkezi</h2><p>Arama talebi, terk edilen sepetler, ürün performansı ve satış trendleri.</p></div></div>
<div class="metric-grid metric-grid-4"><?=wy_metric((string)$todayViews,'Bugünkü Sayfa Görüntüleme','Toplam ziyaret olayı')?><?=wy_metric((string)$monthOrders,'Aylık Sipariş','Bu ay')?><?=wy_metric(money($monthRevenue),'Aylık Ciro','İptaller hariç','highlight')?><?=wy_metric((string)count(array_filter($abandoned,fn($x)=>(int)$x['idle_minutes']>=30)),'Terk Sepet','30 dk+ hareketsiz')?></div>
<div class="admin-grid-equal"><section class="admin-card"><div class="admin-card-head"><div><h3>Arama Talebi</h3><p>Son 30 gün</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Arama</th><th>Tekrar</th><th>Sonuçsuz</th><th>Sonuç</th></tr></thead><tbody><?php if(!$searches):?><tr><td colspan="4"><?=wy_empty('Arama verisi yok','Aramalar geldikçe burada analiz edilir.')?></td></tr><?php endif;?><?php foreach($searches as $s):?><tr><td><b><?=h($s['search_term'])?></b></td><td><?=(int)$s['searches']?></td><td><span class="<?=((int)$s['noresult']>0)?'stock-low':'stock-ok'?>"><?=(int)$s['noresult']?></span></td><td><?=(int)$s['max_results']?></td></tr><?php endforeach;?></tbody></table></div></section><section class="admin-card"><div class="admin-card-head"><div><h3>Aktif / Terk Edilen Sepetler</h3><p>Müşteri ödeme öncesi davranışı</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Sepet</th><th>Tutar</th><th>E-posta</th><th>Son Hareket</th><th>Durum</th></tr></thead><tbody><?php if(!$abandoned):?><tr><td colspan="5"><?=wy_empty('Sepet yok','Aktif sepetler burada listelenecek.')?></td></tr><?php endif;?><?php foreach($abandoned as $c):?><tr><td>#<?=(int)$c['id']?></td><td><b><?=money($c['subtotal'])?></b></td><td><?=h($c['customer_email'])?></td><td><?=h(date('d.m H:i',strtotime($c['updated_at'])))?></td><td><span class="status <?=(int)$c['idle_minutes']>=30?'cancelled':'active'?>"><?=(int)$c['idle_minutes']>=30?'Terk':'Aktif'?></span></td></tr><?php endforeach;?></tbody></table></div></section></div>
<section class="admin-card"><div class="admin-card-head"><div><h3>Ürün Performansı</h3><p>Görüntülenme, satış adedi, ciro ve yaklaşık brüt marj</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Ürün</th><th>Görüntülenme</th><th>Satılan</th><th>Ciro</th><th>Güncel Marj</th><th>Dönüşüm</th></tr></thead><tbody><?php foreach($topProducts as $p):$margin=(float)$p['sale_price']>0?(((float)$p['sale_price']-(float)$p['purchase_price'])/(float)$p['sale_price']*100):0;$conv=(int)$p['view_count']>0?((float)$p['sold']/(int)$p['view_count']*100):0;?><tr><td><b><?=h($p['name'])?></b><small><?=h($p['sku'])?></small></td><td><?=number_format((int)$p['view_count'])?></td><td><?=number_format((int)$p['sold'])?></td><td><b><?=money($p['revenue'])?></b></td><td>%<?=number_format($margin,1,',','.')?></td><td>%<?=number_format($conv,2,',','.')?></td></tr><?php endforeach;?></tbody></table></div></section>