<?php
$tab=$_GET['tab']??'banners';$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=db()->prepare('SELECT * FROM banners WHERE id=?');$s->execute([$editId]);$edit=$s->fetch();}
$edit=$edit?:['id'=>0,'title'=>'','subtitle'=>'','eyebrow'=>'','desktop_image'=>'','mobile_image'=>'','desktop_width'=>'','desktop_height'=>'','mobile_width'=>'','mobile_height'=>'','link_url'=>'','button_text'=>'','text_color'=>'#ffffff','overlay_color'=>'#000000','overlay_opacity'=>.20,'content_align'=>'left','open_new_tab'=>0,'position_code'=>'home_hero','sort_order'=>0,'start_at'=>'','end_at'=>'','is_active'=>1];
$banners=db()->query('SELECT * FROM banners ORDER BY position_code,sort_order,id')->fetchAll();$sections=db()->query('SELECT * FROM homepage_sections ORDER BY sort_order,id')->fetchAll();$features=db()->query('SELECT * FROM homepage_feature_boxes ORDER BY sort_order,id')->fetchAll();$slots=banner_slots();
?>
<div class="admin-page-head"><div><span class="eyebrow">PAZARLAMA / VİTRİN</span><h2>Banner & Ana Sayfa Yönetimi</h2><p>Hero slider, kampanya görselleri, mobil kırılımlar ve ana sayfa modüllerini kod açmadan yönetin.</p></div><div class="admin-actions"><a target="_blank" class="admin-btn light" href="<?=app_url()?>">Ana Sayfayı Gör ↗</a><?php if($editId):?><a class="admin-btn primary" href="?page=banners">+ Yeni Banner</a><?php endif;?></div></div>
<div class="admin-tabs"><a class="<?=$tab==='banners'?'active':''?>" href="?page=banners&tab=banners">Bannerlar</a><a class="<?=$tab==='sections'?'active':''?>" href="?page=banners&tab=sections">Ana Sayfa Modülleri</a><a class="<?=$tab==='features'?'active':''?>" href="?page=banners&tab=features">Hero Özellik Kutuları</a></div>
<?php if($tab==='banners'):?>
<div class="banner-slot-guide"><?php foreach($slots as $code=>$slot):?><div><span><?=h($slot['label'])?></span><b><?=h($slot['desktop'])?></b><small>Mobil: <?=h($slot['mobile'])?></small></div><?php endforeach;?></div>
<div class="admin-grid-wide">
<section class="admin-card"><div class="admin-card-head"><div><h3><?=$editId?'Banner Düzenle':'Yeni Banner'?></h3><p>Her alan için masaüstü ve mobil görseli ayrı yükleyin.</p></div></div><div class="admin-card-body"><form method="post" enctype="multipart/form-data" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_banner_v5"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><input type="hidden" name="current_desktop" value="<?=h($edit['desktop_image'])?>"><input type="hidden" name="current_mobile" value="<?=h($edit['mobile_image'])?>">
<div class="admin-field full"><label>Banner Alanı *</label><select name="position_code" required><?php foreach($slots as $code=>$slot):?><option value="<?=h($code)?>" <?=$edit['position_code']===$code?'selected':''?>><?=h($slot['label'].' — '.$slot['desktop'].' / Mobil '.$slot['mobile'])?></option><?php endforeach;?></select></div>
<div class="admin-field"><label>Üst Etiket</label><input name="eyebrow" value="<?=h($edit['eyebrow'])?>" placeholder="TOPLUCA FIRSATLARI"></div><div class="admin-field"><label>Banner Başlığı *</label><input name="title" value="<?=h($edit['title'])?>" required></div><div class="admin-field full"><label>Alt Başlık</label><input name="subtitle" value="<?=h($edit['subtitle'])?>"></div>
<div class="admin-field full"><label>Masaüstü Görsel</label><div class="upload-panel"><input type="file" name="desktop_image" accept="image/jpeg,image/png,image/webp" data-file-preview="#desktopPreview"><span>Önerilen ölçü seçilen banner alanına göre yukarıdaki rehberde belirtilir. WEBP/JPG tercih edin.</span></div><div id="desktopPreview" class="live-preview-grid"><?php if($edit['desktop_image']):?><div class="live-preview-item wide"><img src="<?=app_url($edit['desktop_image'])?>"><small>Mevcut: <?=h(($edit['desktop_width']?:'?').' × '.($edit['desktop_height']?:'?').' px')?></small></div><?php endif;?></div></div>
<div class="admin-field full"><label>Mobil Görsel</label><div class="upload-panel"><input type="file" name="mobile_image" accept="image/jpeg,image/png,image/webp" data-file-preview="#mobilePreview"><span>Mobil için ayrı kompozisyon kullanın; masaüstü görseli otomatik kırpmak yerine özel mobil tasarım önerilir.</span></div><div id="mobilePreview" class="live-preview-grid"><?php if($edit['mobile_image']):?><div class="live-preview-item"><img src="<?=app_url($edit['mobile_image'])?>"><small>Mevcut: <?=h(($edit['mobile_width']?:'?').' × '.($edit['mobile_height']?:'?').' px')?></small></div><?php endif;?></div></div>
<div class="form-section"><h4>Tıklama & Metin</h4></div><div class="admin-field"><label>Buton Metni</label><input name="button_text" value="<?=h($edit['button_text'])?>" placeholder="Şimdi İncele"></div><div class="admin-field half"><label>Bağlantı</label><input name="link_url" value="<?=h($edit['link_url'])?>" placeholder="category.php?slug=kitap veya https://..."></div><div class="admin-field"><label>Metin Hizası</label><select name="content_align"><option value="left" <?=$edit['content_align']==='left'?'selected':''?>>Sol</option><option value="center" <?=$edit['content_align']==='center'?'selected':''?>>Orta</option><option value="right" <?=$edit['content_align']==='right'?'selected':''?>>Sağ</option></select></div><div class="admin-field"><label>Metin Rengi</label><input type="color" name="text_color" value="<?=h($edit['text_color']?:'#ffffff')?>"></div><div class="admin-field"><label>Görsel Üstü Renk</label><input type="color" name="overlay_color" value="<?=h($edit['overlay_color']?:'#000000')?>"></div><div class="admin-field"><label>Overlay Yoğunluğu (0–0.85)</label><input type="number" min="0" max="0.85" step="0.05" name="overlay_opacity" value="<?=h($edit['overlay_opacity'])?>"></div>
<div class="form-section"><h4>Yayın Planı</h4></div><div class="admin-field"><label>Sıra</label><input type="number" name="sort_order" value="<?=h($edit['sort_order'])?>"></div><div class="admin-field"><label>Başlangıç</label><input type="datetime-local" name="start_at" value="<?=h($edit['start_at']?date('Y-m-d\TH:i',strtotime($edit['start_at'])):'')?>"></div><div class="admin-field"><label>Bitiş</label><input type="datetime-local" name="end_at" value="<?=h($edit['end_at']?date('Y-m-d\TH:i',strtotime($edit['end_at'])):'')?>"></div><div class="check-row full"><label><input type="checkbox" name="is_active" value="1" <?=$edit['is_active']?'checked':''?>> Aktif</label><label><input type="checkbox" name="open_new_tab" value="1" <?=$edit['open_new_tab']?'checked':''?>> Yeni sekmede aç</label></div><div class="full"><button class="admin-btn primary large">Bannerı Kaydet</button></div></form></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Mevcut Bannerlar</h3><p><?=count($banners)?> banner</p></div></div><div class="banner-list"><?php if(!$banners)echo wy_empty('Banner yok','İlk bannerınızı soldaki formdan oluşturun.');foreach($banners as $b):$slot=$slots[$b['position_code']]??['label'=>$b['position_code'],'desktop'=>'-','mobile'=>'-'];?><div class="banner-row"><div class="banner-row-media"><?=wy_banner_preview($b['desktop_image'])?></div><div class="banner-row-main"><b><?=h($b['title'])?></b><span><?=h($slot['label'])?></span><small><?php if($b['desktop_width']):?>Gerçek: <?=(int)$b['desktop_width']?> × <?=(int)$b['desktop_height']?> px<?php else:?>Önerilen: <?=h($slot['desktop'])?><?php endif;?></small></div><div><span class="status <?=$b['is_active']?'active':'inactive'?>"><?=$b['is_active']?'Aktif':'Pasif'?></span></div><div class="row-actions"><a class="admin-btn light" href="?page=banners&edit=<?=(int)$b['id']?>">Düzenle</a><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete_banner_v5"><input type="hidden" name="id" value="<?=(int)$b['id']?>"><button class="icon-btn danger" data-confirm="Banner silinsin mi?">×</button></form></div></div><?php endforeach;?></div></section>
</div>
<?php elseif($tab==='sections'):?>
<section class="admin-card"><div class="admin-card-head"><div><h3>Ana Sayfa Modülleri</h3><p>Blokların başlıklarını, sırasını ve görünürlüğünü değiştirin.</p></div></div><div class="admin-card-body"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save_home_sections"><div class="module-editor"><div class="module-head"><span>Modül</span><span>Başlık</span><span>Alt Başlık</span><span>Sıra</span><span>Aktif</span></div><?php foreach($sections as $s):?><div class="module-row"><b><?=h($s['section_type'])?></b><input name="sections[<?=(int)$s['id']?>][title]" value="<?=h($s['title'])?>"><input name="sections[<?=(int)$s['id']?>][subtitle]" value="<?=h($s['subtitle'])?>"><input type="number" name="sections[<?=(int)$s['id']?>][sort_order]" value="<?=(int)$s['sort_order']?>"><label class="switch"><input type="checkbox" name="sections[<?=(int)$s['id']?>][is_active]" value="1" <?=$s['is_active']?'checked':''?>><span></span></label></div><?php endforeach;?></div><div class="form-actions"><button class="admin-btn primary large">Modülleri Kaydet</button></div></form></div></section>
<?php else:?>
<div class="admin-grid-wide"><section class="admin-card"><div class="admin-card-head"><div><h3>Yeni Özellik Kutusu</h3><p>Hero alanının sağındaki güven/avantaj kutuları</p></div></div><div class="admin-card-body"><form method="post" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_feature_box"><div class="admin-field"><label>İkon</label><input name="icon" placeholder="⚡"></div><div class="admin-field half"><label>Başlık</label><input name="title" required></div><div class="admin-field full"><label>Alt Başlık</label><input name="subtitle"></div><div class="admin-field half"><label>Link</label><input name="link_url"></div><div class="admin-field"><label>Sıra</label><input type="number" name="sort_order" value="0"></div><div class="check-row full"><label><input type="checkbox" name="is_active" value="1" checked> Aktif</label></div><div class="full"><button class="admin-btn primary">Kutuyu Ekle</button></div></form></div></section><section class="admin-card"><div class="admin-card-head"><h3>Özellik Kutuları</h3></div><div class="feature-admin-list"><?php foreach($features as $f):?><div class="feature-admin-row"><span class="feature-admin-icon"><?=h($f['icon'])?></span><div><b><?=h($f['title'])?></b><small><?=h($f['subtitle'])?></small></div><span class="status <?=$f['is_active']?'active':'inactive'?>"><?=$f['is_active']?'Aktif':'Pasif'?></span><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete_feature_box"><input type="hidden" name="id" value="<?=(int)$f['id']?>"><button class="icon-btn danger" data-confirm="Kutu silinsin mi?">×</button></form></div><?php endforeach;?></div></section></div>
<?php endif;?>