<?php
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=db()->prepare('SELECT * FROM brands WHERE id=?');$s->execute([$editId]);$edit=$s->fetch();}
$edit=$edit?:['id'=>0,'name'=>'','slug'=>'','logo'=>'','description'=>'','sort_order'=>0,'is_active'=>1];
$brands=db()->query("SELECT b.*,(SELECT COUNT(*) FROM products p WHERE p.brand_id=b.id) product_count FROM brands b ORDER BY b.sort_order,b.name")->fetchAll();
?>
<div class="admin-page-head"><div><span class="eyebrow">KATALOG</span><h2>Marka Yönetimi</h2><p>Marka logolarını, açıklamalarını, sırasını ve ürün ilişkilerini yönetin.</p></div><div class="admin-actions"><?php if($editId):?><a class="admin-btn light" href="?page=brands">+ Yeni Marka</a><?php endif;?></div></div>
<div class="admin-grid-wide">
<section class="admin-card"><div class="admin-card-head"><div><h3><?=$editId?'Marka Düzenle':'Yeni Marka'?></h3><p>Marka vitrini ve ürün filtrelerinde kullanılacak bilgiler</p></div></div><div class="admin-card-body"><form method="post" enctype="multipart/form-data" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_brand"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><input type="hidden" name="current_logo" value="<?=h($edit['logo'])?>"><div class="admin-field full"><label>Marka Adı *</label><input name="name" value="<?=h($edit['name'])?>" required></div><div class="admin-field"><label>SEO URL</label><input name="slug" value="<?=h($edit['slug'])?>"></div><div class="admin-field"><label>Sıra</label><input type="number" name="sort_order" value="<?=h($edit['sort_order'])?>"></div><div class="admin-field full"><label>Marka Logosu</label><div class="upload-panel compact"><input type="file" name="logo" accept="image/jpeg,image/png,image/webp" data-file-preview="#brandPreview"><span>Önerilen şeffaf PNG/WEBP, yatay 600 × 240 px</span></div><div id="brandPreview" class="live-preview-grid"><?php if($edit['logo']):?><div class="live-preview-item"><img src="<?=app_url($edit['logo'])?>"><small>Mevcut logo</small></div><?php endif;?></div></div><div class="admin-field full"><label>Açıklama</label><textarea name="description" rows="6"><?=h($edit['description'])?></textarea></div><div class="check-row full"><label><input type="checkbox" name="is_active" value="1" <?=$edit['is_active']?'checked':''?>> Aktif</label></div><div class="full"><button class="admin-btn primary large">Markayı Kaydet</button></div></form></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Markalar</h3><p><?=count($brands)?> marka</p></div></div><div class="brand-admin-grid"><?php foreach($brands as $b):?><div class="brand-admin-card"><div class="brand-logo-preview"><?php if($b['logo']):?><img src="<?=app_url($b['logo'])?>" alt=""><?php else:?><span><?=h($b['name'])?></span><?php endif;?></div><div class="brand-admin-info"><b><?=h($b['name'])?></b><span><?=(int)$b['product_count']?> ürün</span><span class="status <?=$b['is_active']?'active':'inactive'?>"><?=$b['is_active']?'Aktif':'Pasif'?></span></div><div class="brand-admin-actions"><a target="_blank" class="icon-btn" href="<?=app_url('brand.php?slug='.urlencode($b['slug']))?>">↗</a><a class="admin-btn light" href="?page=brands&edit=<?=(int)$b['id']?>">Düzenle</a></div></div><?php endforeach;?></div></section>
</div>