<?php
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$s=db()->prepare('SELECT * FROM categories WHERE id=?');$s->execute([$editId]);$edit=$s->fetch();}
$edit=$edit?:['id'=>0,'parent_id'=>'','name'=>'','slug'=>'','icon'=>'','image'=>'','description'=>'','sort_order'=>0,'show_in_menu'=>1,'is_active'=>1,'meta_title'=>'','meta_description'=>'','meta_keywords'=>''];
$cats=db()->query("SELECT c.*,p.name parent_name,(SELECT COUNT(*) FROM products x WHERE x.category_id=c.id) product_count FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY COALESCE(c.parent_id,0),c.sort_order,c.name")->fetchAll();
?>
<div class="admin-page-head"><div><span class="eyebrow">KATALOG</span><h2>Kategori Ağacı</h2><p>Sınırsız seviyede kategori, menü görünümü, görsel ve SEO alanlarını yönetin.</p></div><div class="admin-actions"><?php if($editId):?><a class="admin-btn light" href="?page=categories">+ Yeni Kategori</a><?php endif;?></div></div>
<div class="admin-grid-wide">
<section class="admin-card"><div class="admin-card-head"><div><h3><?=$editId?'Kategori Düzenle':'Yeni Kategori'?></h3><p>Kategori adı, üst kategori, menü ve arama motoru bilgileri</p></div></div><div class="admin-card-body"><form method="post" enctype="multipart/form-data" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_category_v5"><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><input type="hidden" name="current_image" value="<?=h($edit['image'])?>"><div class="admin-field full"><label>Kategori Adı *</label><input name="name" required value="<?=h($edit['name'])?>"></div><div class="admin-field"><label>Üst Kategori</label><select name="parent_id"><option value="">Ana Kategori</option><?php foreach($cats as $c):if((int)$c['id']===$editId)continue;?><option value="<?=(int)$c['id']?>" <?=(int)$edit['parent_id']===(int)$c['id']?'selected':''?>><?=h(($c['parent_name']?$c['parent_name'].' → ':'').$c['name'])?></option><?php endforeach;?></select></div><div class="admin-field"><label>Sıra</label><input type="number" name="sort_order" value="<?=h($edit['sort_order'])?>"></div><div class="admin-field"><label>Kısa İkon / Sembol</label><input name="icon" value="<?=h($edit['icon'])?>" placeholder="✎ veya kısa sembol"></div><div class="admin-field full"><label>Kategori Görseli</label><div class="upload-panel compact"><input type="file" name="image" accept="image/jpeg,image/png,image/webp" data-file-preview="#catPreview"><span>Önerilen: 1200 × 500 px veya kare ikon • JPG/PNG/WEBP</span></div><div id="catPreview" class="live-preview-grid"><?php if($edit['image']):?><div class="live-preview-item"><img src="<?=app_url($edit['image'])?>"><small>Mevcut görsel</small></div><?php endif;?></div></div><div class="admin-field full"><label>Açıklama</label><textarea name="description" rows="5"><?=h($edit['description'])?></textarea></div><div class="form-section"><h4>SEO</h4></div><div class="admin-field full"><label>SEO URL</label><input name="slug" value="<?=h($edit['slug'])?>" placeholder="Boş bırakırsanız otomatik oluşur"></div><div class="admin-field full"><label>Meta Title</label><input name="meta_title" value="<?=h($edit['meta_title'])?>"></div><div class="admin-field full"><label>Meta Description</label><textarea name="meta_description" rows="3"><?=h($edit['meta_description'])?></textarea></div><div class="admin-field full"><label>Anahtar Kelimeler</label><input name="meta_keywords" value="<?=h($edit['meta_keywords'])?>"></div><div class="check-row full"><label><input type="checkbox" name="show_in_menu" value="1" <?=$edit['show_in_menu']?'checked':''?>> Ana menüde göster</label><label><input type="checkbox" name="is_active" value="1" <?=$edit['is_active']?'checked':''?>> Aktif</label></div><div class="full"><button class="admin-btn primary large">Kategoriyi Kaydet</button></div></form></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Kategoriler</h3><p><?=count($cats)?> kategori kayıtlı</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Kategori</th><th>Üst</th><th>Ürün</th><th>Menü</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($cats as $c):?><tr><td><div class="category-name-cell"><span class="category-icon-mini"><?=h($c['icon']?:'•')?></span><div><b><?=h($c['name'])?></b><small><?=h($c['slug'])?></small></div></div></td><td><?=h($c['parent_name']?:'Ana Kategori')?></td><td><?=(int)$c['product_count']?></td><td><?=$c['show_in_menu']?'Evet':'Hayır'?></td><td><span class="status <?=$c['is_active']?'active':'inactive'?>"><?=$c['is_active']?'Aktif':'Pasif'?></span></td><td><a class="admin-btn light" href="?page=categories&edit=<?=(int)$c['id']?>">Düzenle</a></td></tr><?php endforeach;?></tbody></table></div></section>
</div>