<?php
$id=(int)($_GET['id']??0);$s=db()->prepare('SELECT * FROM orders WHERE id=?');$s->execute([$id]);$o=$s->fetch();if(!$o){echo wy_empty('Sipariş bulunamadı','Geçersiz sipariş kaydı.');return;}$it=db()->prepare('SELECT * FROM order_items WHERE order_id=? ORDER BY id');$it->execute([$id]);$items=$it->fetchAll();$hist=db()->prepare('SELECT h.*,a.username admin_name FROM order_status_history h LEFT JOIN admins a ON a.id=h.admin_id WHERE h.order_id=? ORDER BY h.id DESC');$hist->execute([$id]);$history=$hist->fetchAll();$pay=db()->prepare('SELECT * FROM payments WHERE order_id=? ORDER BY id DESC');$pay->execute([$id]);$payments=$pay->fetchAll();
?>
<div class="admin-page-head"><div><span class="eyebrow">SİPARİŞ</span><h2><?=h($o['order_no'])?></h2><p><?=h(date('d.m.Y H:i',strtotime($o['created_at'])))?> • <?=h($o['customer_name'])?></p></div><div class="admin-actions"><a class="admin-btn light" href="?page=orders">← Siparişler</a><a target="_blank" class="admin-btn light" href="<?=app_url('order-track.php')?>">Takip Sayfası ↗</a></div></div>
<div class="order-summary-grid"><div><span>Toplam</span><b><?=money($o['grand_total'])?></b></div><div><span>Ödeme</span><b><?=h(wy_status_tr($o['payment_status']))?></b></div><div><span>Sipariş Durumu</span><b><?=h(wy_status_tr($o['status']))?></b></div><div><span>Teslimat</span><b><?=h($o['shipping_company_name']?:$o['delivery_method'])?></b></div></div>
<div class="admin-grid-2">
<section class="admin-card"><div class="admin-card-head"><div><h3>Sipariş Kalemleri</h3><p><?=count($items)?> ürün satırı</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Ürün</th><th>Adet</th><th>Birim</th><th>Maliyet</th><th>Toplam</th></tr></thead><tbody><?php foreach($items as $r):?><tr><td><b><?=h($r['product_name'])?></b><small><?=h($r['sku'])?></small></td><td><?=(int)$r['quantity']?></td><td><?=money($r['unit_price'])?></td><td><?=money($r['unit_cost'])?></td><td><b><?=money($r['line_total'])?></b></td></tr><?php endforeach;?></tbody></table></div><div class="order-totals"><div><span>Ara toplam</span><b><?=money($o['subtotal'])?></b></div><div><span>İndirim</span><b>- <?=money($o['discount_total'])?></b></div><div><span>Kargo</span><b><?=money($o['shipping_total'])?></b></div><div class="grand"><span>Genel Toplam</span><b><?=money($o['grand_total'])?></b></div></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Operasyon</h3><p>Durum, ödeme ve kargo takibi</p></div></div><div class="admin-card-body"><form method="post" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_order"><input type="hidden" name="id" value="<?=$id?>"><div class="admin-field full"><label>Sipariş Durumu</label><select name="status"><?php foreach(['new'=>'Yeni','approved'=>'Onaylandı','preparing'=>'Hazırlanıyor','shipped'=>'Kargoda','delivered'=>'Teslim Edildi','cancelled'=>'İptal'] as $k=>$v):?><option value="<?=$k?>" <?=$o['status']===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div class="admin-field full"><label>Ödeme Durumu</label><select name="payment_status"><option value="pending" <?=$o['payment_status']==='pending'?'selected':''?>>Bekliyor</option><option value="paid" <?=$o['payment_status']==='paid'?'selected':''?>>Ödendi</option><option value="failed" <?=$o['payment_status']==='failed'?'selected':''?>>Başarısız</option></select></div><div class="admin-field full"><label>Kargo Takip Numarası</label><input name="tracking_no" value="<?=h($o['tracking_no'])?>"></div><div class="admin-field full"><label>Durum Notu</label><textarea name="status_note" rows="4" placeholder="Müşteriye/operasyona not"></textarea></div><div class="full"><button class="admin-btn primary large">Siparişi Güncelle</button></div></form></div></section>
</div>
<div class="admin-grid-equal"><section class="admin-card"><div class="admin-card-head"><div><h3>Müşteri & Teslimat</h3><p>Adres ve iletişim</p></div></div><div class="admin-card-body detail-list"><div><span>Ad Soyad</span><b><?=h($o['customer_name'])?></b></div><div><span>E-posta</span><b><?=h($o['customer_email'])?></b></div><div><span>Telefon</span><b><?=h($o['customer_phone'])?></b></div><div><span>Adres</span><b><?=h($o['city'].' / '.$o['district'].($o['neighborhood']?' / '.$o['neighborhood']:''))?></b><p><?=nl2br(h($o['address']))?></p></div><div><span>Fatura</span><b><?=$o['billing_same_as_shipping']?'Teslimat adresi ile aynı':h(($o['billing_company']?:'').' '.$o['billing_tax_office'].' '.$o['billing_tax_no'])?></b></div><?php if($o['customer_note']):?><div><span>Müşteri Notu</span><p><?=nl2br(h($o['customer_note']))?></p></div><?php endif;?></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Durum Geçmişi</h3><p>Sipariş üzerinde yapılan işlemler</p></div></div><div class="timeline"><?php if(!$history)echo wy_empty('Hareket yok','Durum güncellendiğinde burada görünür.');foreach($history as $h):?><div class="timeline-item"><span></span><div><b><?=h(wy_status_tr($h['status']))?></b><small><?=h(date('d.m.Y H:i',strtotime($h['created_at'])))?><?= $h['admin_name']?' • '.h($h['admin_name']):''?></small><?php if($h['note']):?><p><?=h($h['note'])?></p><?php endif;?></div></div><?php endforeach;?></div></section></div>