<?php
$q=trim($_GET['q']??'');$brand=(int)($_GET['brand']??0);$cat=(int)($_GET['category']??0);$stock=$_GET['stock']??'';$status=$_GET['status']??'';
$where=['1=1'];$params=[];
if($q!==''){$where[]='(p.name LIKE ? OR p.sku LIKE ? OR p.barcode LIKE ? OR p.isbn LIKE ?)';$like='%'.$q.'%';$params=[$like,$like,$like,$like];}
if($brand){$where[]='p.brand_id=?';$params[]=$brand;}
if($cat){$where[]='p.category_id=?';$params[]=$cat;}
if($stock==='low')$where[]='p.stock<=p.critical_stock';elseif($stock==='out')$where[]='p.stock<=0';
if($status==='active')$where[]='p.is_active=1';elseif($status==='passive')$where[]='p.is_active=0';
$sql="SELECT p.*,b.name brand_name,c.name category_name,(SELECT image_path FROM product_images i WHERE i.product_id=p.id ORDER BY i.is_primary DESC,i.sort_order,i.id LIMIT 1) image FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE ".implode(' AND ',$where).' ORDER BY p.id DESC LIMIT 500';
$s=db()->prepare($sql);$s->execute($params);$rows=$s->fetchAll();
$brands=db()->query('SELECT id,name FROM brands WHERE is_active=1 ORDER BY name')->fetchAll();
$cats=db()->query('SELECT id,name FROM categories WHERE is_active=1 ORDER BY name')->fetchAll();
?>
<div class="admin-page-head"><div><span class="eyebrow">KATALOG</span><h2>Ürün Yönetimi</h2><p>Ürün, görsel, SEO, fiyat, stok, özellik ve toplu alım fiyatlarını tek ekrandan yönetin.</p></div><div class="admin-actions"><a class="admin-btn light" href="export.php">CSV Dışa Aktar</a><a class="admin-btn light" href="?page=products&tab=import">CSV İçe Aktar</a><a class="admin-btn primary" href="?page=product_edit">+ Yeni Ürün</a></div></div>
<?php if(($_GET['tab']??'')==='import'):?><section class="admin-card"><div class="admin-card-head"><div><h3>Toplu Ürün Aktarımı</h3><p>Binlerce ürünü SKU bazlı toplu içe aktarın.</p></div></div><div class="admin-card-body"><form class="import-box" method="post" action="import.php" enctype="multipart/form-data"><div class="upload-panel"><b>CSV dosyanızı seçin</b><span>UTF-8 • ; ayraç • SKU benzersiz olmalı</span><input type="file" name="csv" accept=".csv" required></div><button class="admin-btn primary">Dosyayı İçe Aktar</button></form></div></section><?php endif;?>
<section class="admin-card"><div class="admin-card-head product-toolbar"><form method="get" class="product-filter-bar"><input type="hidden" name="page" value="products"><div class="search-control"><span>⌕</span><input name="q" value="<?=h($q)?>" placeholder="Ürün adı, SKU, barkod veya ISBN"></div><select name="category"><option value="0">Tüm kategoriler</option><?php foreach($cats as $c):?><option value="<?=(int)$c['id']?>" <?=$cat===(int)$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select><select name="brand"><option value="0">Tüm markalar</option><?php foreach($brands as $b):?><option value="<?=(int)$b['id']?>" <?=$brand===(int)$b['id']?'selected':''?>><?=h($b['name'])?></option><?php endforeach;?></select><select name="stock"><option value="">Stok durumu</option><option value="low" <?=$stock==='low'?'selected':''?>>Kritik stok</option><option value="out" <?=$stock==='out'?'selected':''?>>Stokta yok</option></select><select name="status"><option value="">Tüm durumlar</option><option value="active" <?=$status==='active'?'selected':''?>>Aktif</option><option value="passive" <?=$status==='passive'?'selected':''?>>Pasif</option></select><button class="admin-btn dark">Filtrele</button></form><span class="pill"><?=count($rows)?> ürün</span></div>
<div class="table-wrap"><table class="admin-table product-table"><thead><tr><th>Ürün</th><th>Kategori</th><th>Marka</th><th>Alış</th><th>Satış</th><th>Stok</th><th>Görüntülenme</th><th>Durum</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9"><?=wy_empty('Ürün bulunamadı','Filtreleri değiştirin veya yeni ürün ekleyin.')?></td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><div class="table-product"><?php if($r['image']):?><img src="<?=app_url($r['image'])?>" alt=""><?php else:?><span class="product-initial"><?=h(mb_substr($r['name'],0,1))?></span><?php endif;?><div><a class="name" href="?page=product_edit&id=<?=(int)$r['id']?>"><?=h($r['name'])?></a><small><?=h($r['sku'])?><?= $r['barcode']?' · '.h($r['barcode']):''?></small></div></div></td><td><?=h($r['category_name'])?></td><td><?=h($r['brand_name'])?></td><td><?=money($r['purchase_price'])?></td><td><b><?=money($r['sale_price'])?></b></td><td><span class="<?=((int)$r['stock']<=(int)$r['critical_stock'])?'stock-low':'stock-ok'?>"><?=(int)$r['stock']?></span></td><td><?=number_format((int)$r['view_count'])?></td><td><span class="status <?=$r['is_active']?'active':'inactive'?>"><?=$r['is_active']?'Aktif':'Pasif'?></span></td><td><div class="row-actions"><a class="icon-btn" title="Siteyi aç" target="_blank" href="<?=app_url('product.php?slug='.urlencode($r['slug']))?>">↗</a><a class="admin-btn light" href="?page=product_edit&id=<?=(int)$r['id']?>">Düzenle</a></div></td></tr><?php endforeach;?></tbody></table></div></section>