<?php $logo=site_logo_url();$favicon=site_favicon_url();?>
<div class="admin-page-head"><div><span class="eyebrow">SİSTEM / MARKA</span><h2>Site & SEO Ayarları</h2><p>Logo, favicon, SEO, üst duyuru, firma bilgileri, vitrin davranışı ve Havale/EFT ayarlarını tek merkezden yönetin.</p></div><div class="admin-actions"><a target="_blank" class="admin-btn light" href="<?=app_url()?>">Siteyi Gör ↗</a></div></div>
<form method="post" enctype="multipart/form-data" class="admin-card"><?=csrf_field()?><input type="hidden" name="action" value="save_site_identity_51">
<div class="admin-card-head"><div><h3>Marka Kimliği</h3><p>Header, footer, tarayıcı sekmesi ve sosyal paylaşım görselleri</p></div></div>
<div class="admin-card-body"><div class="identity-grid"><div class="identity-preview"><span>Mevcut Logo</span><div class="identity-logo"><img src="<?=h($logo)?>" alt="TOPLUCA"></div><small>Gönderdiğiniz özgün TOPLUCA PNG/WEBP logosunu burada yükleyin. Sistem görseli yeniden çizmez veya oranını değiştirmez; sadece siteye uygun alan içinde contain ile gösterir.</small></div><div class="admin-form"><div class="admin-field full"><label>Site Logosu</label><div class="upload-panel compact"><input type="file" name="site_logo" accept="image/jpeg,image/png,image/webp" data-file-preview="#siteLogoPreview"><span>Önerilen: şeffaf arka planlı yatay PNG/WEBP, yaklaşık 900 × 240 px veya aynı oranlı yüksek çözünürlük.</span></div><div id="siteLogoPreview" class="live-preview-grid"></div></div><div class="admin-field"><label>Favicon</label><input type="file" name="site_favicon" accept="image/png,image/webp,image/jpeg"><small class="field-help">Önerilen: 512 × 512 px kare</small></div><div class="admin-field"><label>Sosyal Paylaşım Görseli</label><input type="file" name="site_og_image" accept="image/png,image/webp,image/jpeg"><small class="field-help">Önerilen: 1200 × 630 px</small></div><div class="admin-field"><label>Kurumsal Vurgu Rengi</label><input type="color" name="theme_accent_color" value="<?=h(setting('theme_accent_color','#ff6000'))?>"><small class="field-help">Standart TOPLUCA turuncusu #ff6000</small></div></div></div></div>

<div class="admin-card-head sub"><div><h3>Üst Duyuru Şeridi</h3><p>Site üstündeki teslimat/kampanya mesajını kod açmadan değiştirin.</p></div></div>
<div class="admin-card-body"><div class="admin-form"><div class="admin-field full"><label>Duyuru Metni</label><input name="announcement_text" maxlength="255" value="<?=h(setting('announcement_text','Ankara’da 15:00’a kadar uygun siparişlerde aynı gün teslimat'))?>"></div><div class="admin-field"><label>Görünürlük</label><label class="switch-line"><input type="checkbox" name="announcement_enabled" value="1" <?=setting('announcement_enabled','1')==='1'?'checked':''?>><span class="switch"><i></i></span> Üst duyuru açık</label></div></div></div>

<div class="admin-card-head sub"><div><h3>Arama Motoru & Site Başlıkları</h3><p>Varsayılan SEO değerleri; ürün ve kategori özel SEO alanları bunların üzerine yazılır.</p></div></div>
<div class="admin-card-body"><div class="admin-form"><div class="admin-field full"><label>Site Title</label><input name="site_title" maxlength="255" value="<?=h(setting('site_title','TOPLUCA'))?>"><small class="field-help">Tarayıcı sekmesi ve arama motoru başlığı. Yaklaşık 50–60 karakter iyi bir hedeftir.</small></div><div class="admin-field full"><label>Meta Description</label><textarea name="site_description" maxlength="500" rows="4"><?=h(setting('site_description',''))?></textarea><small class="field-help">Yaklaşık 140–160 karakter hedefleyin.</small></div><div class="admin-field full"><label>Anahtar Kelimeler</label><textarea name="site_keywords" rows="3"><?=h(setting('site_keywords',''))?></textarea></div><div class="admin-field"><label>Banner Otomatik Geçiş</label><label class="switch-line"><input type="checkbox" name="banner_autoplay" value="1" <?=setting('banner_autoplay','1')==='1'?'checked':''?>><span class="switch"><i></i></span> Aktif</label></div><div class="admin-field"><label>Banner Geçiş Süresi (ms)</label><input type="number" min="2500" max="12000" step="500" name="banner_interval" value="<?=h(setting('banner_interval','5500'))?>"></div></div></div>

<div class="admin-card-head sub"><div><h3>Firma Bilgileri</h3><p>Footer, iletişim ve sipariş ekranlarında kullanılacak kurumsal bilgiler</p></div></div>
<div class="admin-card-body"><div class="admin-form"><div class="admin-field"><label>Firma Adı</label><input name="company_name" value="<?=h(setting('company_name','Yıldız Ofis Kırtasiye'))?>"></div><div class="admin-field"><label>E-posta</label><input type="email" name="company_email" value="<?=h(setting('company_email',''))?>"></div><div class="admin-field"><label>Telefon</label><input name="company_phone" value="<?=h(setting('company_phone',''))?>"></div><div class="admin-field full"><label>Adres</label><textarea name="company_address" rows="3"><?=h(setting('company_address',''))?></textarea></div><div class="admin-field full"><label>Footer Açıklaması</label><textarea name="footer_description" rows="3"><?=h(setting('footer_description',''))?></textarea></div></div></div>

<div class="admin-card-head sub"><div><h3>Havale / EFT</h3><p>Kredi kartı devreye alınana kadar checkout ekranında gösterilecek banka bilgileri</p></div></div>
<div class="admin-card-body"><div class="admin-form"><div class="admin-field"><label>Banka Adı</label><input name="bank_name" value="<?=h(setting('bank_name','Demo Bankası'))?>"></div><div class="admin-field"><label>Hesap Sahibi</label><input name="bank_account_name" value="<?=h(setting('bank_account_name','Yıldız Ofis Kırtasiye'))?>"></div><div class="admin-field"><label>Şube</label><input name="bank_branch" value="<?=h(setting('bank_branch',''))?>"></div><div class="admin-field full"><label>IBAN</label><input name="bank_iban" value="<?=h(setting('bank_iban',''))?>"></div><div class="admin-field full"><label>Ödeme Notu</label><textarea name="bank_payment_note" rows="3"><?=h(setting('bank_payment_note',''))?></textarea></div></div></div>
<div class="sticky-save"><span>Bu ayarlar mağazanın tamamında kullanılır.</span><button class="admin-btn primary large">Site Ayarlarını Kaydet</button></div></form>

<section class="admin-card"><div class="admin-card-head"><div><h3>Yönetici Güvenliği</h3><p>Başlangıç şifresini üretim ortamında mutlaka değiştirin.</p></div></div><div class="admin-card-body"><form method="post" class="admin-form" style="max-width:760px"><?=csrf_field()?><input type="hidden" name="action" value="change_admin_password_v5"><div class="admin-field"><label>Mevcut Şifre</label><input type="password" name="current_password" required></div><div class="admin-field"><label>Yeni Şifre</label><input type="password" name="new_password" minlength="12" required></div><div class="admin-field"><label>Yeni Şifre Tekrar</label><input type="password" name="new_password_confirm" minlength="12" required></div><div class="full"><button class="admin-btn dark">Yönetici Şifresini Değiştir</button></div></form></div></section>