<?php
$themes=builtin_themes();$active=active_theme_key();$manual=(string)setting('active_theme','standard');$auto=setting('theme_auto_schedule','1')==='1';$schedules=db()->query('SELECT * FROM theme_schedules ORDER BY start_at DESC,priority DESC')->fetchAll();$currentSchedule=current_theme_schedule();
?>
<div class="admin-page-head"><div><span class="eyebrow">TASARIM SİSTEMİ</span><h2>Tema Yönetimi</h2><p>TOPLUCA’nın temel yapısını bozmadan özel gün ve mevsim temalarını yönetin.</p></div><div class="admin-actions"><a target="_blank" class="admin-btn light" href="<?=app_url()?>">Canlı Siteyi Gör ↗</a></div></div>
<?php if($currentSchedule):?><div class="admin-alert info"><b>Takvim teması aktif:</b> <?=h($currentSchedule['name'])?> — <?=h($themes[$currentSchedule['theme_key']]['name']??$currentSchedule['theme_key'])?>. Bitiş: <?=h(date('d.m.Y H:i',strtotime($currentSchedule['end_at'])))?></div><?php endif;?>
<section class="admin-card"><div class="admin-card-head"><div><h3>Hazır Profesyonel Temalar</h3><p>Renk ve dekorasyon değişir; kategori, ürün kartı ve checkout yerleşimi korunur.</p></div><span class="pill">Aktif: <?=h($themes[$active]['name']??$active)?></span></div><div class="admin-card-body"><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save_theme"><div class="theme-grid"><?php foreach($themes as $key=>$t):?><label class="theme-card theme-preview-<?=h($key)?> <?=$manual===$key?'selected':''?>"><input type="radio" name="active_theme" value="<?=h($key)?>" <?=$manual===$key?'checked':''?>><div class="theme-preview"><div class="theme-preview-top"></div><div class="theme-preview-hero"><span><?=$t['icon']?></span></div><div class="theme-preview-cards"><i></i><i></i><i></i></div></div><div class="theme-card-info"><b><?=h($t['name'])?></b><span><?=h($t['description'])?></span></div></label><?php endforeach;?></div><div class="theme-save-row"><label class="check-inline"><input type="checkbox" name="theme_auto_schedule" value="1" <?=$auto?'checked':''?>> Tarihli tema planlarını otomatik uygula</label><button class="admin-btn primary large">Tema Ayarını Kaydet</button></div></form></div></section>
<div class="admin-grid-wide">
<section class="admin-card"><div class="admin-card-head"><div><h3>Yeni Tema Takvimi</h3><p>Belirli tarihler arasında tema otomatik devreye girsin.</p></div></div><div class="admin-card-body"><form method="post" class="admin-form"><?=csrf_field()?><input type="hidden" name="action" value="save_theme_schedule"><div class="admin-field full"><label>Plan Adı</label><input name="name" required placeholder="Örn. Ramazan Bayramı 2027"></div><div class="admin-field"><label>Tema</label><select name="theme_key"><?php foreach($themes as $key=>$t):?><option value="<?=h($key)?>"><?=h($t['name'])?></option><?php endforeach;?></select></div><div class="admin-field"><label>Başlangıç</label><input type="datetime-local" name="start_at" required></div><div class="admin-field"><label>Bitiş</label><input type="datetime-local" name="end_at" required></div><div class="admin-field"><label>Öncelik</label><input type="number" name="priority" value="50"><small class="field-help">Özel günlere 100, mevsimlere 10 gibi.</small></div><div class="full"><button class="admin-btn primary">Takvime Ekle</button></div></form></div></section>
<section class="admin-card"><div class="admin-card-head"><div><h3>Tema Takvimi</h3><p>Özel gün ve mevsim planları</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Plan</th><th>Tema</th><th>Başlangıç</th><th>Bitiş</th><th>Öncelik</th><th></th></tr></thead><tbody><?php if(!$schedules):?><tr><td colspan="6"><?=wy_empty('Tema takvimi boş','İsterseniz yukarıdan tarihli tema planı oluşturabilirsiniz.')?></td></tr><?php endif;?><?php foreach($schedules as $r):?><tr><td><b><?=h($r['name'])?></b></td><td><?=h($themes[$r['theme_key']]['name']??$r['theme_key'])?></td><td><?=h(date('d.m.Y H:i',strtotime($r['start_at'])))?></td><td><?=h(date('d.m.Y H:i',strtotime($r['end_at'])))?></td><td><?=(int)$r['priority']?></td><td><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete_theme_schedule"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><button class="icon-btn danger" data-confirm="Tema planı kaldırılsın mı?">×</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
</div>
<div class="info-box"><b>Tasarım prensibi</b><p>Kış temasında yoğun kar efekti, bayramda büyük dekorasyon veya yaz temasında aşırı renk değişimi kullanılmaz. Hazır temalar yalnızca marka çizgisine uyumlu arka plan, ince ikon/doku ve vurgu renkleri değiştirir; alışveriş deneyiminin yerleşimi aynı kalır.</p></div>