<?php
declare(strict_types=1);

function main_categories(): array{return db()->query("SELECT * FROM categories WHERE parent_id IS NULL AND is_active=1 ORDER BY sort_order,name")->fetchAll();}
function category_children(int $parent): array{$s=db()->prepare("SELECT * FROM categories WHERE parent_id=? AND is_active=1 ORDER BY sort_order,name");$s->execute([$parent]);return $s->fetchAll();}
function category_descendants(int $root): array{$ids=[$root];$queue=[$root];while($queue){$id=array_shift($queue);$s=db()->prepare('SELECT id FROM categories WHERE parent_id=? AND is_active=1');$s->execute([$id]);foreach($s->fetchAll() as $r){$cid=(int)$r['id'];if(!in_array($cid,$ids,true)){$ids[]=$cid;$queue[]=$cid;}}}return $ids;}
function product_primary_image(int $productId): ?string{$s=db()->prepare('SELECT image_path FROM product_images WHERE product_id=? ORDER BY is_primary DESC,sort_order,id LIMIT 1');$s->execute([$productId]);$v=$s->fetchColumn();return $v!==false?(string)$v:null;}
function product_images(int $productId): array{$s=db()->prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY is_primary DESC,sort_order,id');$s->execute([$productId]);return $s->fetchAll();}
function product_attributes(int $productId): array{$s=db()->prepare('SELECT * FROM product_attributes WHERE product_id=? ORDER BY sort_order,id');$s->execute([$productId]);return $s->fetchAll();}
function product_tiers(int $productId): array{$s=db()->prepare('SELECT * FROM product_price_tiers WHERE product_id=? AND is_active=1 ORDER BY min_qty');$s->execute([$productId]);return $s->fetchAll();}
function active_campaigns(): array{static $c=null;if($c!==null)return $c;$c=db()->query("SELECT * FROM campaigns WHERE is_active=1 AND (start_at IS NULL OR start_at<=NOW()) AND (end_at IS NULL OR end_at>=NOW())")->fetchAll();return $c;}
function unit_price(array $product,int $qty=1): float{$base=(float)$product['sale_price'];foreach(product_tiers((int)$product['id']) as $t){$min=(int)$t['min_qty'];$max=$t['max_qty']!==null?(int)$t['max_qty']:null;if($qty>=$min&&($max===null||$qty<=$max))$base=(float)$t['unit_price'];}
    $best=$base;foreach(active_campaigns() as $c){$match=$c['scope_type']==='all'||($c['scope_type']==='product'&&(int)$c['scope_id']===(int)$product['id'])||($c['scope_type']==='brand'&&(int)$c['scope_id']===(int)($product['brand_id']??0))||($c['scope_type']==='category'&&(int)$c['scope_id']===(int)$product['category_id']);if(!$match)continue;if($c['min_qty']!==null&&$qty<(int)$c['min_qty'])continue;$candidate=$c['discount_type']==='fixed'?$base-(float)$c['discount_value']:$base*(1-(float)$c['discount_value']/100);$best=min($best,max(0,$candidate));}return round($best,2);}
function product_by_slug(string $slug): ?array{$s=db()->prepare("SELECT p.*,b.name brand_name,b.slug brand_slug,c.name category_name,c.slug category_slug FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.is_active=1 LIMIT 1");$s->execute([$slug]);$r=$s->fetch();return $r?:null;}
function cart_id(): int{$session=session_id();$uid=user_id();$s=db()->prepare('SELECT id FROM carts WHERE session_key=? AND converted_order_id IS NULL ORDER BY id DESC LIMIT 1');$s->execute([$session]);$id=$s->fetchColumn();if($id)return (int)$id;$s=db()->prepare('INSERT INTO carts(session_key,user_id,subtotal,created_at,updated_at) VALUES(?,?,0,NOW(),NOW())');$s->execute([$session,$uid]);return (int)db()->lastInsertId();}
function cart_items(): array{$s=db()->prepare("SELECT ci.id cart_item_id,ci.quantity,p.*,b.name brand_name,c.name category_name FROM cart_items ci JOIN products p ON p.id=ci.product_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE ci.cart_id=? AND p.is_active=1 ORDER BY ci.id DESC");$s->execute([cart_id()]);$rows=$s->fetchAll();foreach($rows as &$r){$r['unit_price']=unit_price($r,(int)$r['quantity']);$r['line_total']=round($r['unit_price']*(int)$r['quantity'],2);$r['primary_image']=product_primary_image((int)$r['id']);}return $rows;}
function cart_subtotal(): float{$t=0;foreach(cart_items() as $r)$t+=(float)$r['line_total'];return round($t,2);}
function cart_count(): int{$n=0;foreach(cart_items() as $r)$n+=(int)$r['quantity'];return $n;}
function cart_sync(): void{$s=db()->prepare('UPDATE carts SET user_id=?,subtotal=?,updated_at=NOW() WHERE id=?');$s->execute([user_id(),cart_subtotal(),cart_id()]);}
function cart_add(int $productId,int $qty): void{$qty=max(1,min(99,$qty));$s=db()->prepare('SELECT stock FROM products WHERE id=? AND is_active=1');$s->execute([$productId]);$stock=$s->fetchColumn();if($stock===false||$stock<=0)throw new RuntimeException('Ürün stokta bulunmuyor.');$s=db()->prepare('SELECT id,quantity FROM cart_items WHERE cart_id=? AND product_id=?');$s->execute([cart_id(),$productId]);$e=$s->fetch();if($e){$new=min((int)$stock,(int)$e['quantity']+$qty);db()->prepare('UPDATE cart_items SET quantity=?,updated_at=NOW() WHERE id=?')->execute([$new,$e['id']]);}else{db()->prepare('INSERT INTO cart_items(cart_id,product_id,quantity,created_at,updated_at) VALUES(?,?,?,NOW(),NOW())')->execute([cart_id(),$productId,min($qty,(int)$stock)]);}cart_sync();}
function cart_update(array $quantities): void{foreach($quantities as $id=>$qty){$qty=(int)$qty;if($qty<=0){db()->prepare('DELETE FROM cart_items WHERE id=? AND cart_id=?')->execute([(int)$id,cart_id()]);continue;}$s=db()->prepare('SELECT p.stock FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.id=? AND ci.cart_id=?');$s->execute([(int)$id,cart_id()]);$stock=(int)$s->fetchColumn();db()->prepare('UPDATE cart_items SET quantity=?,updated_at=NOW() WHERE id=? AND cart_id=?')->execute([min(max(1,$qty),$stock),(int)$id,cart_id()]);}cart_sync();}
function product_card_data(array $p): array{$p['primary_image']=product_primary_image((int)$p['id']);$p['display_price']=unit_price($p,1);$tiers=product_tiers((int)$p['id']);$p['tier_hint']=$tiers?$tiers[0]:null;return $p;}
function search_expand(string $term): array{$norm=normalize_tr($term);$terms=[$term];$s=db()->query('SELECT term,synonyms FROM search_synonyms WHERE is_active=1');foreach($s->fetchAll() as $r){$all=array_map('trim',explode(',',$r['synonyms']));$normalized=array_map('normalize_tr',$all);if(normalize_tr($r['term'])===$norm||in_array($norm,$normalized,true)){$terms=array_merge($terms,$all,[$r['term']]);}}return array_values(array_unique(array_filter($terms)));}
function search_products(string $q,array $filters=[]): array{$terms=search_expand($q);$where=['p.is_active=1'];$params=[];if($q!==''){$parts=[];foreach($terms as $term){$parts[]='(p.name LIKE ? OR p.sku LIKE ? OR p.barcode LIKE ? OR p.isbn LIKE ? OR b.name LIKE ? OR c.name LIKE ?)';$like='%'.$term.'%';for($i=0;$i<6;$i++)$params[]=$like;}$where[]='('.implode(' OR ',$parts).')';}if(!empty($filters['category'])){$where[]='p.category_id=?';$params[]=(int)$filters['category'];}if(!empty($filters['brand'])){$where[]='p.brand_id=?';$params[]=(int)$filters['brand'];}if(isset($filters['min'])&&$filters['min']!==''){$where[]='p.sale_price>=?';$params[]=(float)$filters['min'];}if(isset($filters['max'])&&$filters['max']!==''){$where[]='p.sale_price<=?';$params[]=(float)$filters['max'];}if(!empty($filters['stock']))$where[]='p.stock>0';$order='p.is_featured DESC,p.sales_count DESC,p.id DESC';if(($filters['sort']??'')==='price_asc')$order='p.sale_price ASC';if(($filters['sort']??'')==='price_desc')$order='p.sale_price DESC';if(($filters['sort']??'')==='new')$order='p.id DESC';$sql="SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE ".implode(' AND ',$where).' ORDER BY '.$order.' LIMIT 200';$s=db()->prepare($sql);$s->execute($params);$rows=$s->fetchAll();foreach($rows as &$r)$r=product_card_data($r);return $rows;}
