<?php
declare(strict_types=1);

function schema_sql(): array {
    return [
        "SET FOREIGN_KEY_CHECKS=0",
        "CREATE TABLE IF NOT EXISTS settings (setting_key VARCHAR(190) PRIMARY KEY, setting_value TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, full_name VARCHAR(160) NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL DEFAULT 'superadmin', must_change_password TINYINT(1) NOT NULL DEFAULT 1, is_active TINYINT(1) NOT NULL DEFAULT 1, last_login_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS admin_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id INT UNSIGNED NULL, action_name VARCHAR(120) NOT NULL, entity_type VARCHAR(80) NULL, entity_id BIGINT UNSIGNED NULL, details TEXT NULL, ip_address VARCHAR(64) NULL, created_at DATETIME NOT NULL, INDEX(admin_id,created_at), INDEX(entity_type,entity_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS login_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) NULL, ip_address VARCHAR(64) NULL, created_at DATETIME NOT NULL, INDEX(username,ip_address,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, phone VARCHAR(60) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, email_verified_at DATETIME NULL, last_login_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(phone), INDEX(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS user_addresses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(80) NOT NULL DEFAULT 'Adresim', first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, phone VARCHAR(60) NOT NULL, company VARCHAR(190) NULL, tax_office VARCHAR(120) NULL, tax_no VARCHAR(50) NULL, city VARCHAR(120) NOT NULL, district VARCHAR(120) NOT NULL, neighborhood VARCHAR(160) NULL, address TEXT NOT NULL, postal_code VARCHAR(20) NULL, is_default_shipping TINYINT(1) NOT NULL DEFAULT 0, is_default_billing TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(user_id), INDEX(city,district)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, parent_id INT UNSIGNED NULL, name VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL UNIQUE, icon VARCHAR(80) NULL, image VARCHAR(255) NULL, description TEXT NULL, sort_order INT NOT NULL DEFAULT 0, show_in_menu TINYINT(1) NOT NULL DEFAULT 1, is_active TINYINT(1) NOT NULL DEFAULT 1, meta_title VARCHAR(255) NULL, meta_description VARCHAR(500) NULL, INDEX(parent_id,is_active,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS brands (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL UNIQUE, logo VARCHAR(255) NULL, description TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS products (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, brand_id INT UNSIGNED NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL UNIQUE, sku VARCHAR(120) NOT NULL UNIQUE, barcode VARCHAR(120) NULL, isbn VARCHAR(30) NULL, model_number VARCHAR(120) NULL, short_description VARCHAR(700) NULL, description MEDIUMTEXT NULL, purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0, sale_price DECIMAL(12,2) NOT NULL DEFAULT 0, compare_price DECIMAL(12,2) NULL, vat_rate DECIMAL(6,2) NOT NULL DEFAULT 20, stock INT NOT NULL DEFAULT 0, critical_stock INT NOT NULL DEFAULT 5, weight_kg DECIMAL(8,3) NULL, desi DECIMAL(8,2) NULL, shipping_policy VARCHAR(30) NOT NULL DEFAULT 'standard', same_day_delivery TINYINT(1) NOT NULL DEFAULT 1, is_active TINYINT(1) NOT NULL DEFAULT 1, is_featured TINYINT(1) NOT NULL DEFAULT 0, is_new TINYINT(1) NOT NULL DEFAULT 0, is_bestseller TINYINT(1) NOT NULL DEFAULT 0, view_count BIGINT UNSIGNED NOT NULL DEFAULT 0, sales_count BIGINT UNSIGNED NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(category_id,is_active), INDEX(brand_id,is_active), INDEX(barcode), INDEX(isbn), INDEX(stock), FULLTEXT KEY ft_product_search(name,sku,barcode,short_description)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_categories (product_id INT UNSIGNED NOT NULL, category_id INT UNSIGNED NOT NULL, PRIMARY KEY(product_id,category_id), INDEX(category_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, image_path VARCHAR(255) NOT NULL, alt_text VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, is_primary TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, INDEX(product_id,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_attributes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, attribute_name VARCHAR(160) NOT NULL, attribute_value TEXT NOT NULL, filter_key VARCHAR(160) NULL, sort_order INT NOT NULL DEFAULT 0, INDEX(product_id,sort_order), INDEX(filter_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_price_tiers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, min_qty INT UNSIGNED NOT NULL, max_qty INT UNSIGNED NULL, unit_price DECIMAL(12,2) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, INDEX(product_id,min_qty)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS favorites (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_favorite(user_id,product_id), INDEX(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS carts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_key VARCHAR(190) NOT NULL, user_id BIGINT UNSIGNED NULL, customer_email VARCHAR(190) NULL, subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, converted_order_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(session_key), INDEX(user_id), INDEX(converted_order_id,updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS cart_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, cart_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_cart_product(cart_id,product_id), INDEX(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS shipping_companies (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, code VARCHAR(80) NOT NULL UNIQUE, logo VARCHAR(255) NULL, base_fee DECIMAL(12,2) NOT NULL DEFAULT 0, free_shipping_limit DECIMAL(12,2) NULL, estimated_days VARCHAR(80) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS same_day_districts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, district_name VARCHAR(120) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1, extra_fee DECIMAL(12,2) NOT NULL DEFAULT 0, daily_capacity INT UNSIGNED NULL, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS same_day_holidays (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, holiday_date DATE NOT NULL UNIQUE, note VARCHAR(190) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_no VARCHAR(60) NOT NULL UNIQUE, user_id BIGINT UNSIGNED NULL, customer_name VARCHAR(190) NOT NULL, customer_email VARCHAR(190) NOT NULL, customer_phone VARCHAR(80) NOT NULL, city VARCHAR(120) NOT NULL, district VARCHAR(120) NOT NULL, neighborhood VARCHAR(160) NULL, address TEXT NOT NULL, billing_same_as_shipping TINYINT(1) NOT NULL DEFAULT 1, billing_company VARCHAR(190) NULL, billing_tax_office VARCHAR(120) NULL, billing_tax_no VARCHAR(50) NULL, subtotal DECIMAL(14,2) NOT NULL, discount_total DECIMAL(14,2) NOT NULL DEFAULT 0, shipping_total DECIMAL(14,2) NOT NULL DEFAULT 0, grand_total DECIMAL(14,2) NOT NULL, delivery_method VARCHAR(50) NOT NULL, shipping_company_id INT UNSIGNED NULL, shipping_company_name VARCHAR(190) NULL, tracking_no VARCHAR(120) NULL, payment_method VARCHAR(80) NOT NULL DEFAULT 'bank_transfer', payment_status VARCHAR(60) NOT NULL DEFAULT 'pending', status VARCHAR(60) NOT NULL DEFAULT 'new', customer_note TEXT NULL, account_claim_token_hash VARCHAR(255) NULL, account_claim_expires_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(user_id), INDEX(customer_email), INDEX(status,created_at), INDEX(order_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NULL, product_name VARCHAR(255) NOT NULL, sku VARCHAR(120) NOT NULL, quantity INT UNSIGNED NOT NULL, unit_price DECIMAL(12,2) NOT NULL, unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0, vat_rate DECIMAL(6,2) NOT NULL DEFAULT 20, discount_total DECIMAL(12,2) NOT NULL DEFAULT 0, line_total DECIMAL(14,2) NOT NULL, INDEX(order_id), INDEX(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS order_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, status VARCHAR(60) NOT NULL, note VARCHAR(500) NULL, admin_id INT UNSIGNED NULL, created_at DATETIME NOT NULL, INDEX(order_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(80) NOT NULL DEFAULT 'bank_transfer', provider_transaction_id VARCHAR(190) NULL, amount DECIMAL(14,2) NOT NULL, status VARCHAR(60) NOT NULL DEFAULT 'pending', notes VARCHAR(500) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(order_id), INDEX(provider_transaction_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS banners (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, subtitle VARCHAR(255) NULL, desktop_image VARCHAR(255) NULL, mobile_image VARCHAR(255) NULL, link_url VARCHAR(500) NULL, button_text VARCHAR(120) NULL, position_code VARCHAR(80) NOT NULL DEFAULT 'home_hero', sort_order INT NOT NULL DEFAULT 0, start_at DATETIME NULL, end_at DATETIME NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(position_code,is_active,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS homepage_sections (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, section_type VARCHAR(80) NOT NULL, title VARCHAR(190) NULL, subtitle VARCHAR(255) NULL, reference_id INT UNSIGNED NULL, settings_json LONGTEXT NULL, sort_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(is_active,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS campaigns (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, scope_type VARCHAR(50) NOT NULL DEFAULT 'all', scope_id INT UNSIGNED NULL, discount_type VARCHAR(50) NOT NULL DEFAULT 'percent', discount_value DECIMAL(12,2) NOT NULL DEFAULT 0, min_cart_total DECIMAL(12,2) NULL, min_qty INT UNSIGNED NULL, start_at DATETIME NULL, end_at DATETIME NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(is_active,start_at,end_at), INDEX(scope_type,scope_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS search_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, search_term VARCHAR(255) NOT NULL, normalized_term VARCHAR(255) NULL, result_count INT NOT NULL DEFAULT 0, session_key VARCHAR(190) NULL, user_id BIGINT UNSIGNED NULL, clicked_product_id INT UNSIGNED NULL, added_to_cart TINYINT(1) NOT NULL DEFAULT 0, purchased TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, INDEX(search_term), INDEX(result_count,created_at), INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS search_synonyms (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, term VARCHAR(190) NOT NULL UNIQUE, synonyms TEXT NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS suppliers (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, tax_no VARCHAR(50) NULL, phone VARCHAR(60) NULL, email VARCHAR(190) NULL, address TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS purchases (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, supplier_id INT UNSIGNED NULL, document_no VARCHAR(120) NULL, purchase_date DATE NOT NULL, total DECIMAL(14,2) NOT NULL DEFAULT 0, notes TEXT NULL, created_at DATETIME NOT NULL, INDEX(supplier_id,purchase_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS purchase_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_id BIGINT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL, unit_cost DECIMAL(12,2) NOT NULL, line_total DECIMAL(14,2) NOT NULL, INDEX(purchase_id), INDEX(product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS stock_movements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NOT NULL, movement_type VARCHAR(50) NOT NULL, quantity INT NOT NULL, unit_cost DECIMAL(12,2) NULL, reference_type VARCHAR(60) NULL, reference_id BIGINT UNSIGNED NULL, notes VARCHAR(500) NULL, admin_id INT UNSIGNED NULL, created_at DATETIME NOT NULL, INDEX(product_id,created_at), INDEX(reference_type,reference_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS page_views (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, page_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, session_key VARCHAR(190) NULL, user_id BIGINT UNSIGNED NULL, ip_address VARCHAR(64) NULL, created_at DATETIME NOT NULL, INDEX(page_type,created_at), INDEX(entity_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "SET FOREIGN_KEY_CHECKS=1"
    ];
}

function seed_v4(PDO $pdo): void {
    $settings = [
        'site_name'=>'TOPLUCA','site_url'=>'','free_shipping_limit'=>'750','same_day_enabled'=>'1','same_day_cutoff'=>'15:00','same_day_free_limit'=>'2000','same_day_under_limit_fee'=>'149.90','same_day_allow_paid_under_limit'=>'1','same_day_daily_capacity'=>'60','same_day_weekdays'=>'1,2,3,4,5,6','bank_name_1'=>'Demo Bankası','bank_iban_1'=>'TR00 0000 0000 0000 0000 0000 00','bank_account_1'=>'Yıldız Ofis Kırtasiye','bank_name_2'=>'Örnek Katılım','bank_iban_2'=>'TR11 1111 1111 1111 1111 1111 11','bank_account_2'=>'Yıldız Ofis Kırtasiye','support_phone'=>'0312 000 00 00','support_email'=>'destek@topluca.net','same_day_city'=>'Ankara'
    ];
    $st=$pdo->prepare("INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");
    foreach($settings as $k=>$v){$st->execute([$k,$v]);}

    $st=$pdo->prepare("INSERT INTO admins(username,full_name,password_hash,role,must_change_password,is_active,created_at,updated_at) VALUES('emrah','Emrah',?,'superadmin',1,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE username=username");
    $st->execute([password_hash('emr321456', PASSWORD_DEFAULT)]);

    $main=[
        ['Kırtasiye','kirtasiye','✏',1],['Kitap','kitap','▤',2],['Bilgisayar Sarf Malzemeleri','bilgisayar-sarf-malzemeleri','▣',3],['Yazıcı, Toner & Kartuş','yazici-toner-kartus','▧',4],['Kağıt & Ofis Ürünleri','kagit-ofis-urunleri','▱',5],['Okul Ürünleri','okul-urunleri','▰',6],['Hobi & Sanat','hobi-sanat','◉',7]
    ];
    $catIds=[];
    foreach($main as $c){$s=$pdo->prepare("INSERT INTO categories(parent_id,name,slug,icon,sort_order,show_in_menu,is_active) VALUES(NULL,?,?,?,?,1,1) ON DUPLICATE KEY UPDATE name=VALUES(name),icon=VALUES(icon),sort_order=VALUES(sort_order)");$s->execute([$c[0],$c[1],$c[2],$c[3]]);$q=$pdo->prepare("SELECT id FROM categories WHERE slug=?");$q->execute([$c[1]]);$catIds[$c[1]]=(int)$q->fetchColumn();}

    $children=[
        ['kirtasiye','Kalemler','kalemler',1],['kirtasiye','Defter & Ajanda','defter-ajanda',2],['kirtasiye','Dosyalama & Arşivleme','dosyalama-arsivleme',3],['kirtasiye','Yapıştırıcı & Bant','yapistirici-bant',4],
        ['kitap','KPSS','kpss',1],['kitap','YKS','yks',2],['kitap','8. Sınıf','8-sinif',3],['kitap','7. Sınıf','7-sinif',4],['kitap','6. Sınıf','6-sinif',5],['kitap','5. Sınıf','5-sinif',6],
        ['bilgisayar-sarf-malzemeleri','Mouse','mouse',1],['bilgisayar-sarf-malzemeleri','Klavye','klavye',2],['bilgisayar-sarf-malzemeleri','RAM','ram',3],['bilgisayar-sarf-malzemeleri','SSD & HDD','ssd-hdd',4],['bilgisayar-sarf-malzemeleri','Kablolar & Adaptörler','kablolar-adaptorler',5],
        ['yazici-toner-kartus','Toner','toner',1],['yazici-toner-kartus','Kartuş','kartus',2],['yazici-toner-kartus','Yazıcılar','yazicilar',3],
        ['kagit-ofis-urunleri','Fotokopi Kağıdı','fotokopi-kagidi',1],['kagit-ofis-urunleri','Etiket & Zarf','etiket-zarf',2],['kagit-ofis-urunleri','Hesap Makineleri','hesap-makineleri',3],
        ['okul-urunleri','Okul Çantaları','okul-cantalari',1],['okul-urunleri','Kalemlik & Matara','kalemlik-matara',2],['okul-urunleri','Geometri Setleri','geometri-setleri',3],
        ['hobi-sanat','Resim Boyaları','resim-boyalari',1],['hobi-sanat','Fırça & Tuval','firca-tuval',2],['hobi-sanat','El İşi & Hobi','el-isi-hobi',3]
    ];
    $childIds=[];
    foreach($children as $c){$p=$catIds[$c[0]];$s=$pdo->prepare("INSERT INTO categories(parent_id,name,slug,sort_order,show_in_menu,is_active) VALUES(?,?,?,?,1,1) ON DUPLICATE KEY UPDATE name=VALUES(name),parent_id=VALUES(parent_id),sort_order=VALUES(sort_order)");$s->execute([$p,$c[1],$c[2],$c[3]]);$q=$pdo->prepare("SELECT id FROM categories WHERE slug=?");$q->execute([$c[2]]);$childIds[$c[2]]=(int)$q->fetchColumn();}

    $kpss=$childIds['kpss'];
    foreach([['GY-GK Lisans','kpss-gygk-lisans',1],['GY-GK Önlisans-Lise','kpss-onlisans-lise',2],['AGS','ags',3]] as $x){$s=$pdo->prepare("INSERT INTO categories(parent_id,name,slug,sort_order,show_in_menu,is_active) VALUES(?,?,?,?,1,1) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),name=VALUES(name)");$s->execute([$kpss,$x[0],$x[1],$x[2]]);}
    $q=$pdo->query("SELECT id FROM categories WHERE slug='kpss-gygk-lisans'");$kpssL=(int)$q->fetchColumn();
    foreach([['Konu Anlatımı','kpss-lisans-konu',1],['Soru Bankası','kpss-lisans-soru-bankasi',2],['Deneme','kpss-lisans-deneme',3],['Yaprak Test','kpss-lisans-yaprak-test',4]] as $x){$s=$pdo->prepare("INSERT INTO categories(parent_id,name,slug,sort_order,show_in_menu,is_active) VALUES(?,?,?,?,0,1) ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id),name=VALUES(name)");$s->execute([$kpssL,$x[0],$x[1],$x[2]]);}
    $q=$pdo->query("SELECT id FROM categories WHERE slug='kpss-lisans-soru-bankasi'");$bookCat=(int)$q->fetchColumn();

    $brands=['Faber-Castell','İksir Yayıncılık','Logitech','HP','Navigator','TOPLUCA','Artline'];$brandIds=[];
    foreach($brands as $i=>$name){$slug=strtolower(iconv('UTF-8','ASCII//TRANSLIT',$name));$slug=preg_replace('/[^a-z0-9]+/','-',$slug);$slug=trim($slug,'-');$s=$pdo->prepare("INSERT INTO brands(name,slug,is_active,sort_order,created_at,updated_at) VALUES(?,?,1,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name)");$s->execute([$name,$slug,$i+1]);$q=$pdo->prepare("SELECT id FROM brands WHERE slug=?");$q->execute([$slug]);$brandIds[$name]=(int)$q->fetchColumn();}

    $products=[
        [$childIds['kalemler'],$brandIds['Faber-Castell'],'Faber-Castell Grip Tükenmez Kalem Mavi 10’lu','TPL-KRT-001','869000000001',72,119.90,139.90,96,'standard'],
        [$bookCat,$brandIds['İksir Yayıncılık'],'KPSS GY-GK Lisans Bağlam Temelli Soru Bankası','TPL-KTP-001','9786250000001',210,349.90,399.90,120,'standard'],
        [$childIds['mouse'],$brandIds['Logitech'],'Logitech M220 Sessiz Kablosuz Mouse Siyah','TPL-BLG-001','5099206066199',315,499,549,48,'free'],
        [$childIds['toner'],$brandIds['HP'],'HP 107A Uyumlu Siyah Toner','TPL-TNR-001','193905000001',360,599,699,35,'free'],
        [$childIds['fotokopi-kagidi'],$brandIds['Navigator'],'Navigator A4 Fotokopi Kağıdı 80 gr 500 Yaprak','TPL-KGT-001','560202400001',145,189.90,209.90,240,'standard'],
        [$childIds['okul-cantalari'],$brandIds['TOPLUCA'],'TOPLUCA Günlük Okul Çantası Siyah','TPL-OKL-001','869000000006',420,699,799,28,'free'],
        [$childIds['resim-boyalari'],$brandIds['Artline'],'Akrilik Boya Başlangıç Seti 12 Renk','TPL-HOB-001','869000000007',165,279.90,319.90,41,'standard']
    ];
    foreach($products as $i=>$p){$slug=strtolower(iconv('UTF-8','ASCII//TRANSLIT',$p[2]));$slug=preg_replace('/[^a-z0-9]+/','-',$slug);$slug=trim($slug,'-');$s=$pdo->prepare("INSERT INTO products(category_id,brand_id,name,slug,sku,barcode,short_description,description,purchase_price,sale_price,compare_price,vat_rate,stock,critical_stock,shipping_policy,same_day_delivery,is_active,is_featured,is_new,is_bestseller,sales_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?, ?,?,?,?,?,?,5,?,1,1,1,1,1,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),category_id=VALUES(category_id),brand_id=VALUES(brand_id),sale_price=VALUES(sale_price),stock=VALUES(stock)");$s->execute([$p[0],$p[1],$p[2],$slug,$p[3],$p[4],'TOPLUCA demo ürünü. Yönetim panelinden tüm ürün bilgilerini, görselleri, stok ve fiyatları düzenleyebilirsiniz.','Profesyonel e-ticaret akışını göstermek için eklenmiş örnek üründür.',$p[5],$p[6],$p[7],20,$p[8],$p[9],20+$i*11]);}

    $pdo->exec("INSERT INTO product_price_tiers(product_id,min_qty,max_qty,unit_price,is_active) SELECT id,5,9,ROUND(sale_price*0.96,2),1 FROM products WHERE NOT EXISTS(SELECT 1 FROM product_price_tiers t WHERE t.product_id=products.id AND t.min_qty=5)");
    $pdo->exec("INSERT INTO product_price_tiers(product_id,min_qty,max_qty,unit_price,is_active) SELECT id,10,NULL,ROUND(sale_price*0.92,2),1 FROM products WHERE NOT EXISTS(SELECT 1 FROM product_price_tiers t WHERE t.product_id=products.id AND t.min_qty=10)");

    $pdo->exec("INSERT INTO shipping_companies(name,code,base_fee,free_shipping_limit,estimated_days,is_active,sort_order) VALUES('Yurtiçi Kargo','yurtici',89.90,750,'1-3 iş günü',1,1),('MNG Kargo','mng',84.90,750,'1-3 iş günü',1,2),('Aras Kargo','aras',87.90,750,'1-3 iş günü',1,3) ON DUPLICATE KEY UPDATE name=VALUES(name),base_fee=VALUES(base_fee)");
    $districts=['Çankaya','Yenimahalle','Keçiören','Mamak','Etimesgut','Sincan','Altındağ','Gölbaşı','Pursaklar'];$st=$pdo->prepare("INSERT INTO same_day_districts(district_name,is_active,sort_order) VALUES(?,1,?) ON DUPLICATE KEY UPDATE district_name=VALUES(district_name)");foreach($districts as $i=>$d){$st->execute([$d,$i+1]);}
    $syn=['mouse'=>'mouse,mause,fare','hoparlör'=>'hoparlör,speaker,ses bombası','hard disk'=>'hard disk,harddisk,hdd','usb bellek'=>'usb bellek,flash bellek,flash disk','fotokopi kağıdı'=>'fotokopi kağıdı,a4 kağıt,kopya kağıdı'];$st=$pdo->prepare("INSERT INTO search_synonyms(term,synonyms,is_active,created_at,updated_at) VALUES(?,?,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE synonyms=VALUES(synonyms)");foreach($syn as $k=>$v){$st->execute([$k,$v]);}
    $pdo->exec("INSERT INTO homepage_sections(section_type,title,subtitle,sort_order,is_active,created_at,updated_at) VALUES('hero','TOPLUCA','İhtiyacın olan ne varsa, Topluca.',1,1,NOW(),NOW()),('categories','Kategoriler','Ne arıyorsanız burada',2,1,NOW(),NOW()),('bestsellers','Çok Satanlar','En çok tercih edilen ürünler',3,1,NOW(),NOW()),('promo','Avantajlı Alışveriş','Toplu alımlarda daha avantajlı fiyatlar',4,1,NOW(),NOW()),('featured','Öne Çıkanlar','Sizin için seçtiklerimiz',5,1,NOW(),NOW()),('brands','Popüler Markalar','Güvendiğiniz markalar',6,1,NOW(),NOW())");
    $pdo->exec("INSERT INTO banners(title,subtitle,position_code,link_url,button_text,sort_order,is_active,created_at,updated_at) VALUES('Ofis ve okul ihtiyaçların TOPLUCA’da','Kırtasiye, kitap, teknoloji ve daha fazlası tek sepette.','home_hero','search.php','Alışverişe Başla',1,1,NOW(),NOW()),('Kitaplarda Avantajlı Fiyatlar','Sınav hazırlık ve yardımcı kaynaklar','home_mid_left','category.php?slug=kitap','Kitapları İncele',1,1,NOW(),NOW()),('Teknoloji Fırsatları','Bilgisayar bileşenleri ve aksesuarlar','home_mid_right','category.php?slug=bilgisayar-sarf-malzemeleri','Ürünleri İncele',1,1,NOW(),NOW())");
}

function drop_topluca_tables(PDO $pdo): void {
    $tables=['page_views','stock_movements','purchase_items','purchases','suppliers','search_synonyms','search_logs','campaigns','homepage_sections','banners','payments','order_status_history','order_items','orders','same_day_holidays','same_day_districts','shipping_companies','cart_items','carts','favorites','product_price_tiers','product_attributes','product_images','product_categories','products','brands','categories','user_addresses','users','login_attempts','admin_logs','admins','settings'];
    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($tables as $t){$pdo->exec('DROP TABLE IF EXISTS `'.$t.'`');}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
}
