<?php
declare(strict_types=1);

function normalize_files_array(array $files): array{
    $out=[];if(!isset($files['name']))return $out;
    if(!is_array($files['name']))return [$files];
    foreach($files['name'] as $i=>$name){$out[]=['name'=>$name,'type'=>$files['type'][$i]??'','tmp_name'=>$files['tmp_name'][$i]??'','error'=>$files['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$files['size'][$i]??0];}
    return $out;
}

if(($_GET['action']??'')==='export_products'){
    require_admin();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="topluca-urunler-'.date('Ymd-His').'.csv"');$o=fopen('php://output','w');fwrite($o,"\xEF\xBB\xBF");fputcsv($o,['id','sku','barcode','name','brand','category','purchase_price','sale_price','stock','active'],';');$q=db()->query("SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id");foreach($q as $r)fputcsv($o,[$r['id'],$r['sku'],$r['barcode'],$r['name'],$r['brand_name'],$r['category_name'],$r['purchase_price'],$r['sale_price'],$r['stock'],$r['is_active']],';');fclose($o);exit;
}

if($_SERVER['REQUEST_METHOD']!=='POST')return;
csrf_check();$action=$_POST['action']??'';
try{
    if($action==='save_product'){
        $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$sku=trim($_POST['sku']??'');if($name===''||$sku==='')throw new RuntimeException('Ürün adı ve stok kodu zorunludur.');$slug=trim($_POST['slug']??'')?:slugify($name);$data=[(int)$_POST['category_id'],($_POST['brand_id']??'')!==''?(int)$_POST['brand_id']:null,$name,$slug,$sku,trim($_POST['barcode']??'')?:null,trim($_POST['isbn']??'')?:null,trim($_POST['model_number']??'')?:null,trim($_POST['short_description']??'')?:null,trim($_POST['description']??'')?:null,(float)($_POST['purchase_price']??0),(float)($_POST['sale_price']??0),($_POST['compare_price']??'')!==''?(float)$_POST['compare_price']:null,(float)($_POST['vat_rate']??20),(int)($_POST['stock']??0),(int)($_POST['critical_stock']??5),($_POST['weight_kg']??'')!==''?(float)$_POST['weight_kg']:null,($_POST['desi']??'')!==''?(float)$_POST['desi']:null,$_POST['shipping_policy']??'standard',!empty($_POST['same_day_delivery'])?1:0,!empty($_POST['is_active'])?1:0,!empty($_POST['is_featured'])?1:0,!empty($_POST['is_new'])?1:0,!empty($_POST['is_bestseller'])?1:0];
        if($id){$sql='UPDATE products SET category_id=?,brand_id=?,name=?,slug=?,sku=?,barcode=?,isbn=?,model_number=?,short_description=?,description=?,purchase_price=?,sale_price=?,compare_price=?,vat_rate=?,stock=?,critical_stock=?,weight_kg=?,desi=?,shipping_policy=?,same_day_delivery=?,is_active=?,is_featured=?,is_new=?,is_bestseller=?,updated_at=NOW() WHERE id=?';$data[]=$id;db()->prepare($sql)->execute($data);admin_log('product_update','product',$id,$name);}else{$sql='INSERT INTO products(category_id,brand_id,name,slug,sku,barcode,isbn,model_number,short_description,description,purchase_price,sale_price,compare_price,vat_rate,stock,critical_stock,weight_kg,desi,shipping_policy,same_day_delivery,is_active,is_featured,is_new,is_bestseller,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())';db()->prepare($sql)->execute($data);$id=(int)db()->lastInsertId();admin_log('product_create','product',$id,$name);}
        db()->prepare('DELETE FROM product_attributes WHERE product_id=?')->execute([$id]);$attrLines=preg_split('/\r\n|\r|\n/',trim($_POST['attributes_text']??''));$as=db()->prepare('INSERT INTO product_attributes(product_id,attribute_name,attribute_value,filter_key,sort_order) VALUES(?,?,?,?,?)');$sort=1;foreach($attrLines as $line){if(strpos($line,':')===false)continue;list($k,$v)=array_map('trim',explode(':',$line,2));if($k!==''&&$v!=='')$as->execute([$id,$k,$v,slugify($k),$sort++]);}
        db()->prepare('DELETE FROM product_price_tiers WHERE product_id=?')->execute([$id]);$mins=$_POST['tier_min']??[];$maxs=$_POST['tier_max']??[];$prices=$_POST['tier_price']??[];$ts=db()->prepare('INSERT INTO product_price_tiers(product_id,min_qty,max_qty,unit_price,is_active) VALUES(?,?,?,?,1)');foreach($mins as $i=>$min){$min=(int)$min;$price=(float)($prices[$i]??0);if($min>0&&$price>0)$ts->execute([$id,$min,($maxs[$i]??'')!==''?(int)$maxs[$i]:null,$price]);}
        if(!empty($_FILES['images'])){foreach(normalize_files_array($_FILES['images']) as $file){if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;$path=upload_image($file,'products');if($path){$count=(int)db()->prepare('SELECT COUNT(*) FROM product_images WHERE product_id=?')->execute([$id]);$primary=(int)db()->query('SELECT COUNT(*) FROM product_images WHERE product_id='.(int)$id)->fetchColumn()===0?1:0;db()->prepare('INSERT INTO product_images(product_id,image_path,alt_text,sort_order,is_primary,created_at) VALUES(?,?,?,?,?,NOW())')->execute([$id,$path,$name,0,$primary]);}}}
        flash('success','Ürün ve ürün detayları kaydedildi.');redirect_to('webyonet/?page=product_edit&id='.$id);
    }
    if($action==='delete_product_image'){$id=(int)$_POST['image_id'];$s=db()->prepare('SELECT * FROM product_images WHERE id=?');$s->execute([$id]);$im=$s->fetch();if($im){db()->prepare('DELETE FROM product_images WHERE id=?')->execute([$id]);$f=dirname(__DIR__).'/'.$im['image_path'];if(is_file($f))@unlink($f);admin_log('product_image_delete','product',(int)$im['product_id'],$im['image_path']);}flash('success','Görsel kaldırıldı.');redirect_to('webyonet/?page=product_edit&id='.(int)$_POST['product_id']);}
    if($action==='save_category'){$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');if(!$name)throw new RuntimeException('Kategori adı zorunludur.');$slug=trim($_POST['slug']??'')?:slugify($name);$parent=($_POST['parent_id']??'')!==''?(int)$_POST['parent_id']:null;$vals=[$parent,$name,$slug,trim($_POST['icon']??''),trim($_POST['description']??''),(int)($_POST['sort_order']??0),!empty($_POST['show_in_menu'])?1:0,!empty($_POST['is_active'])?1:0];if($id){$vals[]=$id;db()->prepare('UPDATE categories SET parent_id=?,name=?,slug=?,icon=?,description=?,sort_order=?,show_in_menu=?,is_active=? WHERE id=?')->execute($vals);}else{db()->prepare('INSERT INTO categories(parent_id,name,slug,icon,description,sort_order,show_in_menu,is_active) VALUES(?,?,?,?,?,?,?,?)')->execute($vals);$id=(int)db()->lastInsertId();}admin_log('category_save','category',$id,$name);flash('success','Kategori kaydedildi.');redirect_to('webyonet/?page=categories');}
    if($action==='save_brand'){$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');if(!$name)throw new RuntimeException('Marka adı zorunludur.');$slug=trim($_POST['slug']??'')?:slugify($name);$logo=trim($_POST['current_logo']??'');if(!empty($_FILES['logo']['name']))$logo=upload_image($_FILES['logo'],'brands')?:$logo;$vals=[$name,$slug,$logo?:null,trim($_POST['description']??''),!empty($_POST['is_active'])?1:0,(int)($_POST['sort_order']??0)];if($id){$vals[]=$id;db()->prepare('UPDATE brands SET name=?,slug=?,logo=?,description=?,is_active=?,sort_order=?,updated_at=NOW() WHERE id=?')->execute($vals);}else{db()->prepare('INSERT INTO brands(name,slug,logo,description,is_active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,NOW(),NOW())')->execute($vals);$id=(int)db()->lastInsertId();}admin_log('brand_save','brand',$id,$name);flash('success','Marka kaydedildi.');redirect_to('webyonet/?page=brands');}
    if($action==='save_order'){$id=(int)$_POST['id'];$status=$_POST['status']??'new';$payment=$_POST['payment_status']??'pending';$tracking=trim($_POST['tracking_no']??'');$note=trim($_POST['status_note']??'');db()->prepare('UPDATE orders SET status=?,payment_status=?,tracking_no=?,updated_at=NOW() WHERE id=?')->execute([$status,$payment,$tracking?:null,$id]);db()->prepare('INSERT INTO order_status_history(order_id,status,note,admin_id,created_at) VALUES(?,?,?,?,NOW())')->execute([$id,$status,$note?:null,admin_id()]);db()->prepare('UPDATE payments SET status=?,updated_at=NOW() WHERE order_id=?')->execute([$payment,$id]);admin_log('order_update','order',$id,$status.' / '.$payment);flash('success','Sipariş güncellendi.');redirect_to('webyonet/?page=order&id='.$id);}
    if($action==='save_shipping_company'){$id=(int)($_POST['id']??0);$vals=[trim($_POST['name']??''),trim($_POST['code']??''),(float)($_POST['base_fee']??0),($_POST['free_shipping_limit']??'')!==''?(float)$_POST['free_shipping_limit']:null,trim($_POST['estimated_days']??''),!empty($_POST['is_active'])?1:0,(int)($_POST['sort_order']??0)];if($id){$vals[]=$id;db()->prepare('UPDATE shipping_companies SET name=?,code=?,base_fee=?,free_shipping_limit=?,estimated_days=?,is_active=?,sort_order=? WHERE id=?')->execute($vals);}else{db()->prepare('INSERT INTO shipping_companies(name,code,base_fee,free_shipping_limit,estimated_days,is_active,sort_order) VALUES(?,?,?,?,?,?,?)')->execute($vals);$id=(int)db()->lastInsertId();}admin_log('shipping_save','shipping',$id,$vals[0]);flash('success','Kargo firması kaydedildi.');redirect_to('webyonet/?page=shipping');}
    if($action==='save_same_day'){$keys=['same_day_enabled','same_day_cutoff','same_day_free_limit','same_day_under_limit_fee','same_day_allow_paid_under_limit','same_day_daily_capacity','same_day_weekdays'];foreach($keys as $k)set_setting($k,(string)($_POST[$k]??''));$districts=$_POST['district_active']??[];$fees=$_POST['district_fee']??[];$caps=$_POST['district_capacity']??[];foreach(db()->query('SELECT id FROM same_day_districts')->fetchAll() as $r){$id=(int)$r['id'];db()->prepare('UPDATE same_day_districts SET is_active=?,extra_fee=?,daily_capacity=? WHERE id=?')->execute([isset($districts[$id])?1:0,(float)($fees[$id]??0),($caps[$id]??'')!==''?(int)$caps[$id]:null,$id]);}admin_log('same_day_update','settings',null,'Ankara aynı gün ayarları');flash('success','Ankara aynı gün teslimat ayarları güncellendi.');redirect_to('webyonet/?page=shipping&tab=sameday');}
    if($action==='add_holiday'){$date=trim($_POST['holiday_date']??'');if($date)db()->prepare('INSERT INTO same_day_holidays(holiday_date,note,is_active) VALUES(?,?,1) ON DUPLICATE KEY UPDATE note=VALUES(note),is_active=1')->execute([$date,trim($_POST['note']??'')]);flash('success','Kapalı gün eklendi.');redirect_to('webyonet/?page=shipping&tab=sameday');}
    if($action==='save_campaign'){$id=(int)($_POST['id']??0);$vals=[trim($_POST['name']??''),$_POST['scope_type']??'all',($_POST['scope_id']??'')!==''?(int)$_POST['scope_id']:null,$_POST['discount_type']??'percent',(float)($_POST['discount_value']??0),($_POST['min_cart_total']??'')!==''?(float)$_POST['min_cart_total']:null,($_POST['min_qty']??'')!==''?(int)$_POST['min_qty']:null,($_POST['start_at']??'')?:null,($_POST['end_at']??'')?:null,!empty($_POST['is_active'])?1:0];if($id){$vals[]=$id;db()->prepare('UPDATE campaigns SET name=?,scope_type=?,scope_id=?,discount_type=?,discount_value=?,min_cart_total=?,min_qty=?,start_at=?,end_at=?,is_active=?,updated_at=NOW() WHERE id=?')->execute($vals);}else{db()->prepare('INSERT INTO campaigns(name,scope_type,scope_id,discount_type,discount_value,min_cart_total,min_qty,start_at,end_at,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())')->execute($vals);$id=(int)db()->lastInsertId();}admin_log('campaign_save','campaign',$id,$vals[0]);flash('success','Kampanya kaydedildi.');redirect_to('webyonet/?page=campaigns');}
    if($action==='save_banner'){$id=(int)($_POST['id']??0);$desktop=trim($_POST['current_desktop']??'');$mobile=trim($_POST['current_mobile']??'');if(!empty($_FILES['desktop_image']['name']))$desktop=upload_image($_FILES['desktop_image'],'banners')?:$desktop;if(!empty($_FILES['mobile_image']['name']))$mobile=upload_image($_FILES['mobile_image'],'banners')?:$mobile;$vals=[trim($_POST['title']??''),trim($_POST['subtitle']??''),$desktop?:null,$mobile?:null,trim($_POST['link_url']??''),trim($_POST['button_text']??''),$_POST['position_code']??'home_hero',(int)($_POST['sort_order']??0),($_POST['start_at']??'')?:null,($_POST['end_at']??'')?:null,!empty($_POST['is_active'])?1:0];if($id){$vals[]=$id;db()->prepare('UPDATE banners SET title=?,subtitle=?,desktop_image=?,mobile_image=?,link_url=?,button_text=?,position_code=?,sort_order=?,start_at=?,end_at=?,is_active=?,updated_at=NOW() WHERE id=?')->execute($vals);}else{db()->prepare('INSERT INTO banners(title,subtitle,desktop_image,mobile_image,link_url,button_text,position_code,sort_order,start_at,end_at,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())')->execute($vals);$id=(int)db()->lastInsertId();}admin_log('banner_save','banner',$id,$vals[0]);flash('success','Banner kaydedildi.');redirect_to('webyonet/?page=banners');}
    if($action==='save_home_sections'){foreach($_POST['sections']??[] as $id=>$row){db()->prepare('UPDATE homepage_sections SET title=?,subtitle=?,sort_order=?,is_active=?,updated_at=NOW() WHERE id=?')->execute([trim($row['title']??''),trim($row['subtitle']??''),(int)($row['sort_order']??0),!empty($row['is_active'])?1:0,(int)$id]);}admin_log('homepage_sections_update','homepage');flash('success','Ana sayfa modülleri güncellendi.');redirect_to('webyonet/?page=banners&tab=sections');}
    if($action==='save_supplier'){$name=trim($_POST['name']??'');if(!$name)throw new RuntimeException('Tedarikçi adı zorunludur.');db()->prepare('INSERT INTO suppliers(name,tax_no,phone,email,address,is_active,created_at,updated_at) VALUES(?,?,?,?,?,1,NOW(),NOW())')->execute([$name,trim($_POST['tax_no']??''),trim($_POST['phone']??''),trim($_POST['email']??''),trim($_POST['address']??'')]);admin_log('supplier_create','supplier',(int)db()->lastInsertId(),$name);flash('success','Tedarikçi eklendi.');redirect_to('webyonet/?page=purchases');}
    if($action==='save_purchase'){$supplier=(int)($_POST['supplier_id']??0);$product=(int)($_POST['product_id']??0);$qty=(int)($_POST['quantity']??0);$cost=(float)($_POST['unit_cost']??0);if(!$product||$qty<=0||$cost<=0)throw new RuntimeException('Ürün, miktar ve alış maliyeti zorunludur.');db()->beginTransaction();$st=db()->prepare('INSERT INTO purchases(supplier_id,document_no,purchase_date,total,notes,created_at) VALUES(?,?,?,?,?,NOW())');$st->execute([$supplier?:null,trim($_POST['document_no']??''),$_POST['purchase_date']??date('Y-m-d'),$qty*$cost,trim($_POST['notes']??'')]);$purchase=(int)db()->lastInsertId();db()->prepare('INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost,line_total) VALUES(?,?,?,?,?)')->execute([$purchase,$product,$qty,$cost,$qty*$cost]);db()->prepare('UPDATE products SET stock=stock+?,purchase_price=?,updated_at=NOW() WHERE id=?')->execute([$qty,$cost,$product]);db()->prepare("INSERT INTO stock_movements(product_id,movement_type,quantity,unit_cost,reference_type,reference_id,notes,admin_id,created_at) VALUES(?,'purchase',?,?, 'purchase',?,'Mal alış girişi',?,NOW())")->execute([$product,$qty,$cost,$purchase,admin_id()]);db()->commit();admin_log('purchase_create','purchase',$purchase,'Stok girişi');flash('success','Alış ve stok girişi kaydedildi.');redirect_to('webyonet/?page=purchases');}
    if($action==='save_settings'){$keys=['site_name','free_shipping_limit','support_phone','support_email','bank_name_1','bank_account_1','bank_iban_1','bank_name_2','bank_account_2','bank_iban_2'];foreach($keys as $k)set_setting($k,(string)($_POST[$k]??''));admin_log('settings_update','settings');flash('success','Site ayarları kaydedildi.');redirect_to('webyonet/?page=settings');}
    if($action==='change_admin_password'){$a=current_admin();$current=(string)($_POST['current_password']??'');$new=(string)($_POST['new_password']??'');if(!$a||!password_verify($current,$a['password_hash']))throw new RuntimeException('Mevcut şifre yanlış.');if(strlen($new)<12)throw new RuntimeException('Yeni yönetici şifresi en az 12 karakter olmalıdır.');db()->prepare('UPDATE admins SET password_hash=?,must_change_password=0,updated_at=NOW() WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$a['id']]);admin_log('admin_password_change','admin',(int)$a['id']);flash('success','Yönetici şifresi değiştirildi.');redirect_to('webyonet/?page=settings&tab=security');}
    if($action==='import_csv'){
        if(empty($_FILES['csv']['tmp_name']))throw new RuntimeException('CSV dosyası seçin.');$fh=fopen($_FILES['csv']['tmp_name'],'r');if(!$fh)throw new RuntimeException('CSV açılamadı.');$header=fgetcsv($fh,0,';');$count=0;while(($row=fgetcsv($fh,0,';'))!==false){$d=array_combine($header,$row);if(!$d||empty($d['sku'])||empty($d['name']))continue;$cat=(int)($d['category_id']??0);if(!$cat)continue;$brand=($d['brand_id']??'')!==''?(int)$d['brand_id']:null;$slug=slugify($d['name']).'-'.strtolower(substr(md5($d['sku']),0,5));$s=db()->prepare('INSERT INTO products(category_id,brand_id,name,slug,sku,barcode,purchase_price,sale_price,vat_rate,stock,critical_stock,shipping_policy,same_day_delivery,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),barcode=VALUES(barcode),purchase_price=VALUES(purchase_price),sale_price=VALUES(sale_price),stock=VALUES(stock),updated_at=NOW()');$s->execute([$cat,$brand,$d['name'],$slug,$d['sku'],$d['barcode']??null,(float)($d['purchase_price']??0),(float)($d['sale_price']??0),(float)($d['vat_rate']??20),(int)($d['stock']??0),(int)($d['critical_stock']??5),$d['shipping_policy']??'standard']);$count++;}fclose($fh);admin_log('product_csv_import','product',null,$count.' kayıt');flash('success',$count.' ürün CSV’den işlendi.');redirect_to('webyonet/?page=products&tab=import');
    }
}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();flash('error',$e->getMessage());$back=$_SERVER['HTTP_REFERER']??app_url('webyonet/');header('Location: '.$back);exit;}
