<?php
require dirname(__DIR__).'/app/bootstrap.php';require_admin();$error='';$done='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  csrf_check();
  try{
    if(empty($_FILES['csv']['name'])||($_FILES['csv']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('CSV dosyası seçin.');
    if(($_FILES['csv']['size']??0)>8*1024*1024)throw new RuntimeException('CSV dosyası 8 MB sınırını aşamaz.');
    $fh=fopen($_FILES['csv']['tmp_name'],'r');if(!$fh)throw new RuntimeException('CSV açılamadı.');$first=fgets($fh);if($first===false)throw new RuntimeException('CSV boş.');$first=preg_replace('/^\xEF\xBB\xBF/','',$first);$delimiter=substr_count($first,';')>=substr_count($first,',')?';':',';$headers=str_getcsv(trim($first),$delimiter);$headers=array_map(fn($x)=>trim((string)$x),$headers);$required=['sku','name','category_slug','sale_price','stock'];foreach($required as $req)if(!in_array($req,$headers,true))throw new RuntimeException('Eksik kolon: '.$req);
    $updated=0;$created=0;$line=1;db()->beginTransaction();
    while(($row=fgetcsv($fh,0,$delimiter))!==false){$line++;if(count($row)===1&&trim((string)$row[0])==='')continue;$data=[];foreach($headers as $i=>$key)$data[$key]=trim((string)($row[$i]??''));if(($data['sku']??'')===''||($data['name']??'')==='')continue;
      $s=db()->prepare('SELECT id FROM categories WHERE slug=? LIMIT 1');$s->execute([$data['category_slug']]);$categoryId=$s->fetchColumn();if(!$categoryId)throw new RuntimeException($line.'. satırda kategori bulunamadı: '.$data['category_slug']);
      $brandId=null;if(!empty($data['brand'])){$slug=topluca_slug($data['brand']);$s=db()->prepare('SELECT id FROM brands WHERE slug=? LIMIT 1');$s->execute([$slug]);$brandId=$s->fetchColumn();if(!$brandId){db()->prepare('INSERT INTO brands(name,slug,is_active,created_at,updated_at) VALUES(?,?,1,NOW(),NOW())')->execute([$data['brand'],$slug]);$brandId=(int)db()->lastInsertId();}}
      $s=db()->prepare('SELECT id FROM products WHERE sku=? LIMIT 1');$s->execute([$data['sku']]);$id=$s->fetchColumn();$shipping=in_array($data['shipping_policy']??'standard',['standard','free','special'],true)?$data['shipping_policy']:'standard';
      if($id){db()->prepare('UPDATE products SET category_id=?,brand_id=?,name=?,barcode=?,isbn=?,purchase_price=?,sale_price=?,compare_price=?,vat_rate=?,stock=?,critical_stock=?,shipping_policy=?,same_day_delivery=?,is_active=?,updated_at=NOW() WHERE id=?')->execute([(int)$categoryId,$brandId,$data['name'],$data['barcode']?:null,$data['isbn']?:null,(float)($data['purchase_price']??0),(float)$data['sale_price'],($data['compare_price']??'')!==''?(float)$data['compare_price']:null,(float)($data['vat_rate']??20),(int)$data['stock'],(int)($data['critical_stock']??5),$shipping,(int)($data['same_day_delivery']??1),(int)($data['is_active']??1),(int)$id]);$updated++;}
      else{$slug=topluca_slug($data['name']).'-'.topluca_slug($data['sku']);db()->prepare('INSERT INTO products(category_id,brand_id,name,slug,sku,barcode,isbn,purchase_price,sale_price,compare_price,vat_rate,stock,reserved_stock,critical_stock,min_order_qty,shipping_policy,same_day_delivery,is_active,rating_avg,review_count,view_count,sales_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0,?,1,?,?,?,5,0,0,0,NOW(),NOW())')->execute([(int)$categoryId,$brandId,$data['name'],$slug,$data['sku'],$data['barcode']?:null,$data['isbn']?:null,(float)($data['purchase_price']??0),(float)$data['sale_price'],($data['compare_price']??'')!==''?(float)$data['compare_price']:null,(float)($data['vat_rate']??20),(int)$data['stock'],(int)($data['critical_stock']??5),$shipping,(int)($data['same_day_delivery']??1),(int)($data['is_active']??1)]);$created++;}
    }
    fclose($fh);db()->commit();admin_log('import','products',null,"$created yeni, $updated güncel");$done="$created ürün oluşturuldu, $updated ürün güncellendi.";
  }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}
}
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CSV İçe / Dışa | TOPLUCA WebYönet</title><link rel="stylesheet" href="<?=asset('css/admin.css')?>?v=3.0.0"></head><body><div class="admin-login"><section class="admin-login__visual"><div class="admin-login__logo"><?php $logoClass='';require dirname(__DIR__).'/includes/logo.php';?></div><div><h1>Toplu ürün yönetimi, <span>daha hızlı.</span></h1><p>Binlerce ürünü CSV ile güncelleyin; stok, fiyat ve marka bilgilerini topluca yönetin.</p></div><small>TOPLUCA WebYönet · CSV</small></section><section class="admin-login__formwrap"><div class="admin-login__card" style="width:min(620px,100%)"><h2>CSV İçe / Dışa Aktar</h2><p>Excel'de UTF-8 CSV olarak kaydedip yükleyebilirsiniz. Noktalı virgül ve virgül ayırıcı desteklenir.</p><?php if($error):?><div class="admin-flash error"><?=h($error)?></div><?php endif;?><?php if($done):?><div class="admin-flash success"><?=h($done)?></div><?php endif;?><div class="admin-actions" style="margin-bottom:16px"><a class="admin-btn outline" href="<?=url('webyonet/index.php?module=products')?>">← WebYönet</a><a class="admin-btn green" href="<?=url('webyonet/export.php?type=products')?>">Ürün Şablonu / Dışa Aktar ↓</a></div><form method="post" enctype="multipart/form-data"><?=csrf_field()?><label class="field">Ürün CSV Dosyası<input type="file" name="csv" accept=".csv,text/csv" required></label><div class="admin-alert" style="margin-top:12px"><b>Zorunlu kolonlar:</b> sku, name, category_slug, sale_price, stock.<br><b>Desteklenen diğer kolonlar:</b> brand, barcode, isbn, purchase_price, compare_price, vat_rate, critical_stock, shipping_policy, same_day_delivery, is_active.<br>Aynı SKU mevcutsa ürün güncellenir; yoksa yeni ürün açılır.</div><button class="admin-btn" style="width:100%;min-height:42px">CSV'yi Kontrol Et ve İçeri Al</button></form></div></section></div></body></html>
